#ifndef DISPLAYSETTINGS_H
#define DISPLAYSETTINGS_H

#include <QVariant>

class DisplaySettings
{
public:
    enum DisplaySize{
        ds35,
        ds43,
        ds50,
        ds70,
    };

    enum DisplayGeneration{
        dgEve1,
        dgEve2,
        dgEve3
    };

    static DisplaySettings& getInstance() {
        static  DisplaySettings instance;
        return instance;
    }

    DisplaySize getDisplaySize() const;
    void setDisplaySize(const DisplaySize &displaySize);

    DisplayGeneration getDisplayGeneration() const;
    void setDisplayGeneration(const DisplayGeneration &disGen);
    void autoDetectDisplayGeneration();

    uint32_t operator[](const QString property);


private:
    DisplaySettings();
    ~DisplaySettings () { }
    DisplaySettings (const DisplaySettings & ) = delete;
    DisplaySettings & operator=( DisplaySettings & ) = delete;
    QString displaySizeToString(DisplaySize ds);
    QString displayGenerationToString(DisplayGeneration dg);

    DisplaySize mDisplaySize;
    QMap<QString, uint16_t> mapDisplaySizeSettings;
    DisplayGeneration mDisplayGeneration;
    QMap<QString, uint32_t> mapDisplayOptions;
};

#define EVE1        (DisplaySettings::getInstance().getDisplayGeneration()==DisplaySettings::dgEve1)
#define EVE2        (DisplaySettings::getInstance().getDisplayGeneration()==DisplaySettings::dgEve2)
#define EVE3        (DisplaySettings::getInstance().getDisplayGeneration()==DisplaySettings::dgEve3)

#define FT_ROM_CHIPID					0x0C0000UL

//Display Parameters
#define DispWidth                                 (DisplaySettings::getInstance()["__DispWidth"                     ])
#define DispHeight                                (DisplaySettings::getInstance()["__DispHeight"                    ])
#define DispHCycle                                (DisplaySettings::getInstance()["__DispHCycle"                    ])
#define DispHOffset                               (DisplaySettings::getInstance()["__DispHOffset"                   ])
#define DispHSync0                                (DisplaySettings::getInstance()["__DispHSync0"                    ])
#define DispHSync1                                (DisplaySettings::getInstance()["__DispHSync1"                    ])
#define DispVCycle                                (DisplaySettings::getInstance()["__DispVCycle"                    ])
#define DispVOffset                               (DisplaySettings::getInstance()["__DispVOffset"                   ])
#define DispVSync0                                (DisplaySettings::getInstance()["__DispVSync0"                    ])
#define DispVSync1                                (DisplaySettings::getInstance()["__DispVSync1"                    ])
#define DispPCLK                                  (DisplaySettings::getInstance()["__DispPCLK"                      ])
#define DispSwizzle                               (DisplaySettings::getInstance()["__DispSwizzle"                   ])
#define DispPCLKPol                               (DisplaySettings::getInstance()["__DispPCLKPol"                   ])
#define DispCSpread                               (DisplaySettings::getInstance()["__DispCSpread"                   ])
#define DispDither                                (DisplaySettings::getInstance()["__DispDither"                    ])
#define DispRotate                                (DisplaySettings::getInstance()["__DispRotate"                    ])

//EVE3 defines
#define LOW_FREQ_BOUND                            (DisplaySettings::getInstance()["__LOW_FREQ_BOUND"                ])
#define RAM_G_SIZE                                (DisplaySettings::getInstance()["__RAM_G_SIZE"                    ])
#define FLASH_DEFAULT_SHA1KEY	                  (DisplaySettings::getInstance()["__FLASH_DEFAULT_SHA1KEY"         ])
#define PPC                                       (DisplaySettings::getInstance()["__PPC"                           ])
#define BANKS                                     (DisplaySettings::getInstance()["__BANKS"                         ])
#define BANKW                                     (DisplaySettings::getInstance()["__BANKW"                         ])
#define ADC_DIFFERENTIAL                          (DisplaySettings::getInstance()["__ADC_DIFFERENTIAL"              ])
#define ADC_SINGLE_ENDED                          (DisplaySettings::getInstance()["__ADC_SINGLE_ENDED"              ])
#define ADPCM_SAMPLES                             (DisplaySettings::getInstance()["__ADPCM_SAMPLES"                 ])
#define ALPHA                                     (DisplaySettings::getInstance()["__ALPHA"                         ])
#define ALWAYS                                    (DisplaySettings::getInstance()["__ALWAYS"                        ])
#define ANIM_HOLD                                 (DisplaySettings::getInstance()["__ANIM_HOLD"                     ])
#define ANIM_LOOP                                 (DisplaySettings::getInstance()["__ANIM_LOOP"                     ])
#define ANIM_ONCE                                 (DisplaySettings::getInstance()["__ANIM_ONCE"                     ])
#define ARGB1555                                  (DisplaySettings::getInstance()["__ARGB1555"                      ])
#define ARGB2                                     (DisplaySettings::getInstance()["__ARGB2"                         ])
#define ARGB4                                     (DisplaySettings::getInstance()["__ARGB4"                         ])
#define BARGRAPH                                  (DisplaySettings::getInstance()["__BARGRAPH"                      ])
#define BILINEAR                                  (DisplaySettings::getInstance()["__BILINEAR"                      ])
#define BITMAPS                                   (DisplaySettings::getInstance()["__BITMAPS"                       ])
#define BLUE                                      (DisplaySettings::getInstance()["__BLUE"                          ])
#define BORDER                                    (DisplaySettings::getInstance()["__BORDER"                        ])
#define CMDBUF_SIZE                               (DisplaySettings::getInstance()["__CMDBUF_SIZE"                   ])
#define CMD_ANIMDRAW                              (DisplaySettings::getInstance()["__CMD_ANIMDRAW"                  ])
#define CMD_ANIMFRAME                             (DisplaySettings::getInstance()["__CMD_ANIMFRAME"                 ])
#define CMD_ANIMSTART                             (DisplaySettings::getInstance()["__CMD_ANIMSTART"                 ])
#define CMD_ANIMSTOP                              (DisplaySettings::getInstance()["__CMD_ANIMSTOP"                  ])
#define CMD_ANIMXY                                (DisplaySettings::getInstance()["__CMD_ANIMXY"                    ])
#define CMD_APPEND                                (DisplaySettings::getInstance()["__CMD_APPEND"                    ])
#define CMD_APPENDF                               (DisplaySettings::getInstance()["__CMD_APPENDF"                   ])
#define CMD_BGCOLOR                               (DisplaySettings::getInstance()["__CMD_BGCOLOR"                   ])
#define CMD_BITMAP_TRANSFORM                      (DisplaySettings::getInstance()["__CMD_BITMAP_TRANSFORM"          ])
#define CMD_BUTTON                                (DisplaySettings::getInstance()["__CMD_BUTTON"                    ])
#define CMD_CALIBRATE                             (DisplaySettings::getInstance()["__CMD_CALIBRATE"                 ])
#define CMD_CLEARCACHE                            (DisplaySettings::getInstance()["__CMD_CLEARCACHE"                ])
#define CMD_CLOCK                                 (DisplaySettings::getInstance()["__CMD_CLOCK"                     ])
#define CMD_COLDSTART                             (DisplaySettings::getInstance()["__CMD_COLDSTART"                 ])
#define CMD_CRC                                   (DisplaySettings::getInstance()["__CMD_CRC"                       ])
#define CMD_DEPRECATED_CSKETCH                    (DisplaySettings::getInstance()["__CMD_DEPRECATED_CSKETCH"        ])
#define CMD_DIAL                                  (DisplaySettings::getInstance()["__CMD_DIAL"                      ])
#define CMD_DLSTART                               (DisplaySettings::getInstance()["__CMD_DLSTART"                   ])
#define CMD_EXECUTE                               (DisplaySettings::getInstance()["__CMD_EXECUTE"                   ])
#define CMD_FGCOLOR                               (DisplaySettings::getInstance()["__CMD_FGCOLOR"                   ])
#define CMD_FILLWIDTH                             (DisplaySettings::getInstance()["__CMD_FILLWIDTH"                 ])
#define CMD_FLASHATTACH                           (DisplaySettings::getInstance()["__CMD_FLASHATTACH"               ])
#define CMD_FLASHDETACH                           (DisplaySettings::getInstance()["__CMD_FLASHDETACH"               ])
#define CMD_FLASHERASE                            (DisplaySettings::getInstance()["__CMD_FLASHERASE"                ])
#define CMD_FLASHFAST                             (DisplaySettings::getInstance()["__CMD_FLASHFAST"                 ])
#define CMD_FLASHREAD                             (DisplaySettings::getInstance()["__CMD_FLASHREAD"                 ])
#define CMD_FLASHSOURCE                           (DisplaySettings::getInstance()["__CMD_FLASHSOURCE"               ])
#define CMD_FLASHSPIDESEL                         (DisplaySettings::getInstance()["__CMD_FLASHSPIDESEL"             ])
#define CMD_FLASHSPIRX                            (DisplaySettings::getInstance()["__CMD_FLASHSPIRX"                ])
#define CMD_FLASHSPITX                            (DisplaySettings::getInstance()["__CMD_FLASHSPITX"                ])
#define CMD_FLASHUPDATE                           (DisplaySettings::getInstance()["__CMD_FLASHUPDATE"               ])
#define CMD_FLASHWRITE                            (DisplaySettings::getInstance()["__CMD_FLASHWRITE"                ])
#define CMD_GAUGE                                 (DisplaySettings::getInstance()["__CMD_GAUGE"                     ])
#define CMD_GETMATRIX                             (DisplaySettings::getInstance()["__CMD_GETMATRIX"                 ])
#define CMD_GETPOINT                              (DisplaySettings::getInstance()["__CMD_GETPOINT"                  ])
#define CMD_GETPROPS                              (DisplaySettings::getInstance()["__CMD_GETPROPS"                  ])
#define CMD_GETPTR                                (DisplaySettings::getInstance()["__CMD_GETPTR"                    ])
#define CMD_GRADCOLOR                             (DisplaySettings::getInstance()["__CMD_GRADCOLOR"                 ])
#define CMD_GRADIENT                              (DisplaySettings::getInstance()["__CMD_GRADIENT"                  ])
#define CMD_GRADIENTA                             (DisplaySettings::getInstance()["__CMD_GRADIENTA"                 ])
#define CMD_HAMMERAUX                             (DisplaySettings::getInstance()["__CMD_HAMMERAUX"                 ])
#define CMD_HMAC                                  (DisplaySettings::getInstance()["__CMD_HMAC"                      ])
#define CMD_IDCT_DELETED                          (DisplaySettings::getInstance()["__CMD_IDCT_DELETED"              ])
#define CMD_INFLATE                               (DisplaySettings::getInstance()["__CMD_INFLATE"                   ])
#define CMD_INFLATE2                              (DisplaySettings::getInstance()["__CMD_INFLATE2"                  ])
#define CMD_INTERRUPT                             (DisplaySettings::getInstance()["__CMD_INTERRUPT"                 ])
#define CMD_INT_RAMSHARED                         (DisplaySettings::getInstance()["__CMD_INT_RAMSHARED"             ])
#define CMD_INT_SWLOADIMAGE                       (DisplaySettings::getInstance()["__CMD_INT_SWLOADIMAGE"           ])
#define CMD_KEYS                                  (DisplaySettings::getInstance()["__CMD_KEYS"                      ])
#define CMD_LAST_                                 (DisplaySettings::getInstance()["__CMD_LAST_"                     ])
#define CMD_LOADIDENTITY                          (DisplaySettings::getInstance()["__CMD_LOADIDENTITY"              ])
#define CMD_LOADIMAGE                             (DisplaySettings::getInstance()["__CMD_LOADIMAGE"                 ])
#define CMD_LOGO                                  (DisplaySettings::getInstance()["__CMD_LOGO"                      ])
#define CMD_MARCH                                 (DisplaySettings::getInstance()["__CMD_MARCH"                     ])
#define CMD_MEDIAFIFO                             (DisplaySettings::getInstance()["__CMD_MEDIAFIFO"                 ])
#define CMD_MEMCPY                                (DisplaySettings::getInstance()["__CMD_MEMCPY"                    ])
#define CMD_MEMCRC                                (DisplaySettings::getInstance()["__CMD_MEMCRC"                    ])
#define CMD_MEMSET                                (DisplaySettings::getInstance()["__CMD_MEMSET"                    ])
#define CMD_MEMWRITE                              (DisplaySettings::getInstance()["__CMD_MEMWRITE"                  ])
#define CMD_MEMZERO                               (DisplaySettings::getInstance()["__CMD_MEMZERO"                   ])
#define CMD_NOP                                   (DisplaySettings::getInstance()["__CMD_NOP"                       ])
#define CMD_NUMBER                                (DisplaySettings::getInstance()["__CMD_NUMBER"                    ])
#define CMD_PLAYVIDEO                             (DisplaySettings::getInstance()["__CMD_PLAYVIDEO"                 ])
#define CMD_PROGRESS                              (DisplaySettings::getInstance()["__CMD_PROGRESS"                  ])
#define CMD_REGREAD                               (DisplaySettings::getInstance()["__CMD_REGREAD"                   ])
#define CMD_RESETFONTS                            (DisplaySettings::getInstance()["__CMD_RESETFONTS"                ])
#define CMD_ROMFONT                               (DisplaySettings::getInstance()["__CMD_ROMFONT"                   ])
#define CMD_ROTATE                                (DisplaySettings::getInstance()["__CMD_ROTATE"                    ])
#define CMD_ROTATEAROUND                          (DisplaySettings::getInstance()["__CMD_ROTATEAROUND"              ])
#define CMD_SCALE                                 (DisplaySettings::getInstance()["__CMD_SCALE"                     ])
#define CMD_SCREENSAVER                           (DisplaySettings::getInstance()["__CMD_SCREENSAVER"               ])
#define CMD_SCROLLBAR                             (DisplaySettings::getInstance()["__CMD_SCROLLBAR"                 ])
#define CMD_SETBASE                               (DisplaySettings::getInstance()["__CMD_SETBASE"                   ])
#define CMD_SETBITMAP                             (DisplaySettings::getInstance()["__CMD_SETBITMAP"                 ])
#define CMD_SETFONT                               (DisplaySettings::getInstance()["__CMD_SETFONT"                   ])
#define CMD_SETFONT2                              (DisplaySettings::getInstance()["__CMD_SETFONT2"                  ])
#define CMD_SETMATRIX                             (DisplaySettings::getInstance()["__CMD_SETMATRIX"                 ])
#define CMD_SETROTATE                             (DisplaySettings::getInstance()["__CMD_SETROTATE"                 ])
#define CMD_SETSCRATCH                            (DisplaySettings::getInstance()["__CMD_SETSCRATCH"                ])
#define CMD_SHA1                                  (DisplaySettings::getInstance()["__CMD_SHA1"                      ])
#define CMD_SKETCH                                (DisplaySettings::getInstance()["__CMD_SKETCH"                    ])
#define CMD_SLIDER                                (DisplaySettings::getInstance()["__CMD_SLIDER"                    ])
#define CMD_SNAPSHOT                              (DisplaySettings::getInstance()["__CMD_SNAPSHOT"                  ])
#define CMD_SNAPSHOT2                             (DisplaySettings::getInstance()["__CMD_SNAPSHOT2"                 ])
#define CMD_SPINNER                               (DisplaySettings::getInstance()["__CMD_SPINNER"                   ])
#define CMD_STOP                                  (DisplaySettings::getInstance()["__CMD_STOP"                      ])
#define CMD_SWAP                                  (DisplaySettings::getInstance()["__CMD_SWAP"                      ])
#define CMD_SYNC                                  (DisplaySettings::getInstance()["__CMD_SYNC"                      ])
#define CMD_TEXT                                  (DisplaySettings::getInstance()["__CMD_TEXT"                      ])
#define CMD_TOGGLE                                (DisplaySettings::getInstance()["__CMD_TOGGLE"                    ])
#define CMD_TOUCH_TRANSFORM                       (DisplaySettings::getInstance()["__CMD_TOUCH_TRANSFORM"           ])
#define CMD_TRACK                                 (DisplaySettings::getInstance()["__CMD_TRACK"                     ])
#define CMD_TRANSLATE                             (DisplaySettings::getInstance()["__CMD_TRANSLATE"                 ])
#define CMD_VIDEOFRAME                            (DisplaySettings::getInstance()["__CMD_VIDEOFRAME"                ])
#define CMD_VIDEOSTART                            (DisplaySettings::getInstance()["__CMD_VIDEOSTART"                ])
#define CMD_VIDEOSTARTF                           (DisplaySettings::getInstance()["__CMD_VIDEOSTARTF"               ])
#define COMPRESSED_RGBA_ASTC_10x10_KHR            (DisplaySettings::getInstance()["__COMPRESSED_RGBA_ASTC_10x10_KHR"])
#define COMPRESSED_RGBA_ASTC_10x5_KHR             (DisplaySettings::getInstance()["__COMPRESSED_RGBA_ASTC_10x5_KHR" ])
#define COMPRESSED_RGBA_ASTC_10x6_KHR             (DisplaySettings::getInstance()["__COMPRESSED_RGBA_ASTC_10x6_KHR" ])
#define COMPRESSED_RGBA_ASTC_10x8_KHR             (DisplaySettings::getInstance()["__COMPRESSED_RGBA_ASTC_10x8_KHR" ])
#define COMPRESSED_RGBA_ASTC_12x10_KHR            (DisplaySettings::getInstance()["__COMPRESSED_RGBA_ASTC_12x10_KHR"])
#define COMPRESSED_RGBA_ASTC_12x12_KHR            (DisplaySettings::getInstance()["__COMPRESSED_RGBA_ASTC_12x12_KHR"])
#define COMPRESSED_RGBA_ASTC_4x4_KHR              (DisplaySettings::getInstance()["__COMPRESSED_RGBA_ASTC_4x4_KHR"  ])
#define COMPRESSED_RGBA_ASTC_5x4_KHR              (DisplaySettings::getInstance()["__COMPRESSED_RGBA_ASTC_5x4_KHR"  ])
#define COMPRESSED_RGBA_ASTC_5x5_KHR              (DisplaySettings::getInstance()["__COMPRESSED_RGBA_ASTC_5x5_KHR"  ])
#define COMPRESSED_RGBA_ASTC_6x5_KHR              (DisplaySettings::getInstance()["__COMPRESSED_RGBA_ASTC_6x5_KHR"  ])
#define COMPRESSED_RGBA_ASTC_6x6_KHR              (DisplaySettings::getInstance()["__COMPRESSED_RGBA_ASTC_6x6_KHR"  ])
#define COMPRESSED_RGBA_ASTC_8x5_KHR              (DisplaySettings::getInstance()["__COMPRESSED_RGBA_ASTC_8x5_KHR"  ])
#define COMPRESSED_RGBA_ASTC_8x6_KHR              (DisplaySettings::getInstance()["__COMPRESSED_RGBA_ASTC_8x6_KHR"  ])
#define COMPRESSED_RGBA_ASTC_8x8_KHR              (DisplaySettings::getInstance()["__COMPRESSED_RGBA_ASTC_8x8_KHR"  ])
#define CTOUCH_MODE_COMPATIBILITY                 (DisplaySettings::getInstance()["__CTOUCH_MODE_COMPATIBILITY"     ])
#define CTOUCH_MODE_EXTENDED                      (DisplaySettings::getInstance()["__CTOUCH_MODE_EXTENDED"          ])
#define DECR                                      (DisplaySettings::getInstance()["__DECR"                          ])
#define DLSWAP_DONE                               (DisplaySettings::getInstance()["__DLSWAP_DONE"                   ])
#define DLSWAP_FRAME                              (DisplaySettings::getInstance()["__DLSWAP_FRAME"                  ])
#define DLSWAP_LINE                               (DisplaySettings::getInstance()["__DLSWAP_LINE"                   ])
#define DST_ALPHA                                 (DisplaySettings::getInstance()["__DST_ALPHA"                     ])
#define EDGE_STRIP_A                              (DisplaySettings::getInstance()["__EDGE_STRIP_A"                  ])
#define EDGE_STRIP_B                              (DisplaySettings::getInstance()["__EDGE_STRIP_B"                  ])
#define EDGE_STRIP_L                              (DisplaySettings::getInstance()["__EDGE_STRIP_L"                  ])
#define EDGE_STRIP_R                              (DisplaySettings::getInstance()["__EDGE_STRIP_R"                  ])
#define EQUAL                                     (DisplaySettings::getInstance()["__EQUAL"                         ])
#define FLASH_STATUS_BASIC                        (DisplaySettings::getInstance()["__FLASH_STATUS_BASIC"            ])
#define FLASH_STATUS_DETACHED                     (DisplaySettings::getInstance()["__FLASH_STATUS_DETACHED"         ])
#define FLASH_STATUS_FULL                         (DisplaySettings::getInstance()["__FLASH_STATUS_FULL"             ])
#define FLASH_STATUS_INIT                         (DisplaySettings::getInstance()["__FLASH_STATUS_INIT"             ])
#define GEQUAL                                    (DisplaySettings::getInstance()["__GEQUAL"                        ])
#define GLFORMAT                                  (DisplaySettings::getInstance()["__GLFORMAT"                      ])
#define GREATER                                   (DisplaySettings::getInstance()["__GREATER"                       ])
#define GREEN                                     (DisplaySettings::getInstance()["__GREEN"                         ])
#define INCR                                      (DisplaySettings::getInstance()["__INCR"                          ])
#define INT_CMDEMPTY                              (DisplaySettings::getInstance()["__INT_CMDEMPTY"                  ])
#define INT_CMDFLAG                               (DisplaySettings::getInstance()["__INT_CMDFLAG"                   ])
#define INT_CONVCOMPLETE                          (DisplaySettings::getInstance()["__INT_CONVCOMPLETE"              ])
#define INT_G8                                    (DisplaySettings::getInstance()["__INT_G8"                        ])
#define INT_L8C                                   (DisplaySettings::getInstance()["__INT_L8C"                       ])
#define INT_PLAYBACK                              (DisplaySettings::getInstance()["__INT_PLAYBACK"                  ])
#define INT_SOUND                                 (DisplaySettings::getInstance()["__INT_SOUND"                     ])
#define INT_SWAP                                  (DisplaySettings::getInstance()["__INT_SWAP"                      ])
#define INT_TAG                                   (DisplaySettings::getInstance()["__INT_TAG"                       ])
#define INT_TOUCH                                 (DisplaySettings::getInstance()["__INT_TOUCH"                     ])
#define INT_VGA                                   (DisplaySettings::getInstance()["__INT_VGA"                       ])
#define INVERT                                    (DisplaySettings::getInstance()["__INVERT"                        ])
#define JT_CYA                                    (DisplaySettings::getInstance()["__JT_CYA"                        ])
#define JT_DRIVES                                 (DisplaySettings::getInstance()["__JT_DRIVES"                     ])
#define JT_FRAMES                                 (DisplaySettings::getInstance()["__JT_FRAMES"                     ])
#define JT_ONESHOT                                (DisplaySettings::getInstance()["__JT_ONESHOT"                    ])
#define JT_PEN                                    (DisplaySettings::getInstance()["__JT_PEN"                        ])
#define JT_PWM                                    (DisplaySettings::getInstance()["__JT_PWM"                        ])
#define JT_RI_ADC_MODE                            (DisplaySettings::getInstance()["__JT_RI_ADC_MODE"                ])
#define JT_RI_CHARGE                              (DisplaySettings::getInstance()["__JT_RI_CHARGE"                  ])
#define JT_RI_CTOUCH_EXTENDED                     (DisplaySettings::getInstance()["__JT_RI_CTOUCH_EXTENDED"         ])
#define JT_RI_EHOST_ID                            (DisplaySettings::getInstance()["__JT_RI_EHOST_ID"                ])
#define JT_RI_EHOST_X                             (DisplaySettings::getInstance()["__JT_RI_EHOST_X"                 ])
#define JT_RI_EHOST_Y                             (DisplaySettings::getInstance()["__JT_RI_EHOST_Y"                 ])
#define JT_RI_INT                                 (DisplaySettings::getInstance()["__JT_RI_INT"                     ])
#define JT_RI_MODE                                (DisplaySettings::getInstance()["__JT_RI_MODE"                    ])
#define JT_RI_OVERSAMPLE                          (DisplaySettings::getInstance()["__JT_RI_OVERSAMPLE"              ])
#define JT_RI_RZTHRESH                            (DisplaySettings::getInstance()["__JT_RI_RZTHRESH"                ])
#define JT_RI_SETTLE                              (DisplaySettings::getInstance()["__JT_RI_SETTLE"                  ])
#define JT_RI_SHORTS                              (DisplaySettings::getInstance()["__JT_RI_SHORTS"                  ])
#define JT_RI_UART_BUSY                           (DisplaySettings::getInstance()["__JT_RI_UART_BUSY"               ])
#define JT_RI_XF_AH                               (DisplaySettings::getInstance()["__JT_RI_XF_AH"                   ])
#define JT_RI_XF_AL                               (DisplaySettings::getInstance()["__JT_RI_XF_AL"                   ])
#define JT_RI_XF_BH                               (DisplaySettings::getInstance()["__JT_RI_XF_BH"                   ])
#define JT_RI_XF_BL                               (DisplaySettings::getInstance()["__JT_RI_XF_BL"                   ])
#define JT_RI_XF_CH                               (DisplaySettings::getInstance()["__JT_RI_XF_CH"                   ])
#define JT_RI_XF_CL                               (DisplaySettings::getInstance()["__JT_RI_XF_CL"                   ])
#define JT_RI_XF_DH                               (DisplaySettings::getInstance()["__JT_RI_XF_DH"                   ])
#define JT_RI_XF_DL                               (DisplaySettings::getInstance()["__JT_RI_XF_DL"                   ])
#define JT_RI_XF_EH                               (DisplaySettings::getInstance()["__JT_RI_XF_EH"                   ])
#define JT_RI_XF_EL                               (DisplaySettings::getInstance()["__JT_RI_XF_EL"                   ])
#define JT_RI_XF_FH                               (DisplaySettings::getInstance()["__JT_RI_XF_FH"                   ])
#define JT_RI_XF_FL                               (DisplaySettings::getInstance()["__JT_RI_XF_FL"                   ])
#define JT_RO_ANALOG                              (DisplaySettings::getInstance()["__JT_RO_ANALOG"                  ])
#define JT_RO_CTOUCH_TOUCH0_XY                    (DisplaySettings::getInstance()["__JT_RO_CTOUCH_TOUCH0_XY"        ])
#define JT_RO_CTOUCH_TOUCH4X                      (DisplaySettings::getInstance()["__JT_RO_CTOUCH_TOUCH4X"          ])
#define JT_RO_CTOUCH_TOUCH4Y                      (DisplaySettings::getInstance()["__JT_RO_CTOUCH_TOUCH4Y"          ])
#define JT_RO_CTOUCH_TOUCHA_XY                    (DisplaySettings::getInstance()["__JT_RO_CTOUCH_TOUCHA_XY"        ])
#define JT_RO_CTOUCH_TOUCHB_XY                    (DisplaySettings::getInstance()["__JT_RO_CTOUCH_TOUCHB_XY"        ])
#define JT_RO_CTOUCH_TOUCHC_XY                    (DisplaySettings::getInstance()["__JT_RO_CTOUCH_TOUCHC_XY"        ])
#define JT_RO_DIRECT_XY                           (DisplaySettings::getInstance()["__JT_RO_DIRECT_XY"               ])
#define JT_RO_DIRECT_Z1Z2                         (DisplaySettings::getInstance()["__JT_RO_DIRECT_Z1Z2"             ])
#define JT_RO_EHOST_ACK                           (DisplaySettings::getInstance()["__JT_RO_EHOST_ACK"               ])
#define JT_RO_FAULT                               (DisplaySettings::getInstance()["__JT_RO_FAULT"                   ])
#define JT_RO_INTERRUPT                           (DisplaySettings::getInstance()["__JT_RO_INTERRUPT"               ])
#define JT_RO_RAW_XY                              (DisplaySettings::getInstance()["__JT_RO_RAW_XY"                  ])
#define JT_RO_RZ                                  (DisplaySettings::getInstance()["__JT_RO_RZ"                      ])
#define JT_RO_SCREEN_XY                           (DisplaySettings::getInstance()["__JT_RO_SCREEN_XY"               ])
#define JT_RO_SHORT_DETECT                        (DisplaySettings::getInstance()["__JT_RO_SHORT_DETECT"            ])
#define JT_RO_UART                                (DisplaySettings::getInstance()["__JT_RO_UART"                    ])
#define JT_RO_WAKE                                (DisplaySettings::getInstance()["__JT_RO_WAKE"                    ])
#define JT_R_SCRATCH                              (DisplaySettings::getInstance()["__JT_R_SCRATCH"                  ])
#define JT_SCL                                    (DisplaySettings::getInstance()["__JT_SCL"                        ])
#define JT_SDA                                    (DisplaySettings::getInstance()["__JT_SDA"                        ])
#define JT_TICK                                   (DisplaySettings::getInstance()["__JT_TICK"                       ])
#define JT_XD                                     (DisplaySettings::getInstance()["__JT_XD"                         ])
#define JT_XEOC                                   (DisplaySettings::getInstance()["__JT_XEOC"                       ])
#define JT_XMCLK                                  (DisplaySettings::getInstance()["__JT_XMCLK"                      ])
#define JT_XSAMP_CLK                              (DisplaySettings::getInstance()["__JT_XSAMP_CLK"                  ])
#define KEEP                                      (DisplaySettings::getInstance()["__KEEP"                          ])
#define L1                                        (DisplaySettings::getInstance()["__L1"                            ])
#define L2                                        (DisplaySettings::getInstance()["__L2"                            ])
#define L4                                        (DisplaySettings::getInstance()["__L4"                            ])
#define L8                                        (DisplaySettings::getInstance()["__L8"                            ])
#define LEQUAL                                    (DisplaySettings::getInstance()["__LEQUAL"                        ])
#define LESS                                      (DisplaySettings::getInstance()["__LESS"                          ])
#define LINEAR_SAMPLES                            (DisplaySettings::getInstance()["__LINEAR_SAMPLES"                ])
#define LINES                                     (DisplaySettings::getInstance()["__LINES"                         ])
#define LINE_STRIP                                (DisplaySettings::getInstance()["__LINE_STRIP"                    ])
#define NEAREST                                   (DisplaySettings::getInstance()["__NEAREST"                       ])
#define NEVER                                     (DisplaySettings::getInstance()["__NEVER"                         ])
#define NOTEQUAL                                  (DisplaySettings::getInstance()["__NOTEQUAL"                      ])
#define ONE                                       (DisplaySettings::getInstance()["__ONE"                           ])
#define ONE_MINUS_DST_ALPHA                       (DisplaySettings::getInstance()["__ONE_MINUS_DST_ALPHA"           ])
#define ONE_MINUS_SRC_ALPHA                       (DisplaySettings::getInstance()["__ONE_MINUS_SRC_ALPHA"           ])
#define OPT_CENTER                                (static_cast<uint16_t>(DisplaySettings::getInstance()["__OPT_CENTER"                    ]))
#define OPT_CENTERX                               (static_cast<uint16_t>(DisplaySettings::getInstance()["__OPT_CENTERX"                   ]))
#define OPT_CENTERY                               (static_cast<uint16_t>(DisplaySettings::getInstance()["__OPT_CENTERY"                   ]))
#define OPT_FILL                                  (DisplaySettings::getInstance()["__OPT_FILL"                      ])
#define OPT_FLASH                                 (DisplaySettings::getInstance()["__OPT_FLASH"                     ])
#define OPT_FLAT                                  (static_cast<uint16_t>(DisplaySettings::getInstance()["__OPT_FLAT"                      ]))
#define OPT_FORMAT                                (DisplaySettings::getInstance()["__OPT_FORMAT"                    ])
#define OPT_FULLSCREEN                            (DisplaySettings::getInstance()["__OPT_FULLSCREEN"                ])
#define OPT_MEDIAFIFO                             (DisplaySettings::getInstance()["__OPT_MEDIAFIFO"                 ])
#define OPT_MONO                                  (DisplaySettings::getInstance()["__OPT_MONO"                      ])
#define OPT_NOBACK                                (DisplaySettings::getInstance()["__OPT_NOBACK"                    ])
#define OPT_NODL                                  (DisplaySettings::getInstance()["__OPT_NODL"                      ])
#define OPT_NOHANDS                               (DisplaySettings::getInstance()["__OPT_NOHANDS"                   ])
#define OPT_NOHM                                  (DisplaySettings::getInstance()["__OPT_NOHM"                      ])
#define OPT_NOPOINTER                             (DisplaySettings::getInstance()["__OPT_NOPOINTER"                 ])
#define OPT_NOSECS                                (DisplaySettings::getInstance()["__OPT_NOSECS"                    ])
#define OPT_NOTEAR                                (DisplaySettings::getInstance()["__OPT_NOTEAR"                    ])
#define OPT_NOTICKS                               (DisplaySettings::getInstance()["__OPT_NOTICKS"                   ])
#define OPT_OVERLAY                               (DisplaySettings::getInstance()["__OPT_OVERLAY"                   ])
#define OPT_RIGHTX                                (static_cast<uint16_t>(DisplaySettings::getInstance()["__OPT_RIGHTX"                    ]))
#define OPT_SIGNED                                (DisplaySettings::getInstance()["__OPT_SIGNED"                    ])
#define OPT_SOUND                                 (DisplaySettings::getInstance()["__OPT_SOUND"                     ])
#define PALETTED                                  (DisplaySettings::getInstance()["__PALETTED"                      ])
#define PALETTED4444                              (DisplaySettings::getInstance()["__PALETTED4444"                  ])
#define PALETTED565                               (DisplaySettings::getInstance()["__PALETTED565"                   ])
#define PALETTED8                                 (DisplaySettings::getInstance()["__PALETTED8"                     ])
#define POINTS                                    (DisplaySettings::getInstance()["__FTPOINTS"                      ])
#define FTPOINTS                                  (DisplaySettings::getInstance()["__FTPOINTS"                      ])
#define RAM_BIST                                  (DisplaySettings::getInstance()["__RAM_BIST"                      ])
#define RAM_CMD                                   (DisplaySettings::getInstance()["__RAM_CMD"                       ])
#define RAM_DL                                    (DisplaySettings::getInstance()["__RAM_DL"                        ])
#define RAM_G                                     (DisplaySettings::getInstance()["__RAM_G"                         ])
#define RAM_J1RAM                                 (DisplaySettings::getInstance()["__RAM_J1RAM"                     ])
#define RAM_JTBOOT                                (DisplaySettings::getInstance()["__RAM_JTBOOT"                    ])
#define RAM_REG                                   (DisplaySettings::getInstance()["__RAM_REG"                       ])
#define RAM_ROMSUB                                (DisplaySettings::getInstance()["__RAM_ROMSUB"                    ])
#define RAM_TOP                                   (DisplaySettings::getInstance()["__RAM_TOP"                       ])
#define RECTS                                     (DisplaySettings::getInstance()["__RECTS"                         ])
#define RED                                       (DisplaySettings::getInstance()["__RED"                           ])
#define REG_ADAPTIVE_FRAMERATE                    (DisplaySettings::getInstance()["__REG_ADAPTIVE_FRAMERATE"        ])
#define REG_ANALOG                                (DisplaySettings::getInstance()["__REG_ANALOG"                    ])
#define REG_ANA_COMP                              (DisplaySettings::getInstance()["__REG_ANA_COMP"                  ])
#define REG_ANIM_ACTIVE                           (DisplaySettings::getInstance()["__REG_ANIM_ACTIVE"               ])
#define REG_BIST_EN                               (DisplaySettings::getInstance()["__REG_BIST_EN"                   ])
#define REG_BUSYBITS                              (DisplaySettings::getInstance()["__REG_BUSYBITS"                  ])
#define REG_CLOCK                                 (DisplaySettings::getInstance()["__REG_CLOCK"                     ])
#define REG_CMDB_SPACE                            (DisplaySettings::getInstance()["__REG_CMDB_SPACE"                ])
#define REG_CMDB_WRITE                            (DisplaySettings::getInstance()["__REG_CMDB_WRITE"                ])
#define REG_CMD_DL                                (DisplaySettings::getInstance()["__REG_CMD_DL"                    ])
#define REG_CMD_READ                              (DisplaySettings::getInstance()["__REG_CMD_READ"                  ])
#define REG_CMD_WRITE                             (DisplaySettings::getInstance()["__REG_CMD_WRITE"                 ])
#define REG_CPURESET                              (DisplaySettings::getInstance()["__REG_CPURESET"                  ])
#define REG_CRC                                   (DisplaySettings::getInstance()["__REG_CRC"                       ])
#define REG_CSPREAD                               (DisplaySettings::getInstance()["__REG_CSPREAD"                   ])
#define REG_CTOUCH_EXTENDED                       (DisplaySettings::getInstance()["__REG_CTOUCH_EXTENDED"           ])
#define REG_CTOUCH_TOUCH0_XY                      (DisplaySettings::getInstance()["__REG_CTOUCH_TOUCH0_XY"          ])
#define REG_CTOUCH_TOUCH4_X                       (DisplaySettings::getInstance()["__REG_CTOUCH_TOUCH4_X"           ])
#define REG_CTOUCH_TOUCH4_Y                       (DisplaySettings::getInstance()["__REG_CTOUCH_TOUCH4_Y"           ])
#define REG_CTOUCH_TOUCHA_XY                      (DisplaySettings::getInstance()["__REG_CTOUCH_TOUCHA_XY"          ])
#define REG_CTOUCH_TOUCHB_XY                      (DisplaySettings::getInstance()["__REG_CTOUCH_TOUCHB_XY"          ])
#define REG_CTOUCH_TOUCHC_XY                      (DisplaySettings::getInstance()["__REG_CTOUCH_TOUCHC_XY"          ])
#define REG_CYA0                                  (DisplaySettings::getInstance()["__REG_CYA0"                      ])
#define REG_CYA1                                  (DisplaySettings::getInstance()["__REG_CYA1"                      ])
#define REG_CYA_TOUCH                             (DisplaySettings::getInstance()["__REG_CYA_TOUCH"                 ])
#define REG_DATESTAMP                             (DisplaySettings::getInstance()["__REG_DATESTAMP"                 ])
#define REG_DF_TUNED                              (DisplaySettings::getInstance()["__REG_DF_TUNED"                  ])
#define REG_DITHER                                (DisplaySettings::getInstance()["__REG_DITHER"                    ])
#define REG_DLSWAP                                (DisplaySettings::getInstance()["__REG_DLSWAP"                    ])
#define REG_EHOST_TOUCH_ACK                       (DisplaySettings::getInstance()["__REG_EHOST_TOUCH_ACK"           ])
#define REG_EHOST_TOUCH_ID                        (DisplaySettings::getInstance()["__REG_EHOST_TOUCH_ID"            ])
#define REG_EHOST_TOUCH_X                         (DisplaySettings::getInstance()["__REG_EHOST_TOUCH_X"             ])
#define REG_EHOST_TOUCH_Y                         (DisplaySettings::getInstance()["__REG_EHOST_TOUCH_Y"             ])
#define REG_EJPG_ACC                              (DisplaySettings::getInstance()["__REG_EJPG_ACC"                  ])
#define REG_EJPG_BUSY                             (DisplaySettings::getInstance()["__REG_EJPG_BUSY"                 ])
#define REG_EJPG_DAT                              (DisplaySettings::getInstance()["__REG_EJPG_DAT"                  ])
#define REG_EJPG_DCC                              (DisplaySettings::getInstance()["__REG_EJPG_DCC"                  ])
#define REG_EJPG_DEBUG                            (DisplaySettings::getInstance()["__REG_EJPG_DEBUG"                ])
#define REG_EJPG_DST                              (DisplaySettings::getInstance()["__REG_EJPG_DST"                  ])
#define REG_EJPG_FORMAT                           (DisplaySettings::getInstance()["__REG_EJPG_FORMAT"               ])
#define REG_EJPG_H                                (DisplaySettings::getInstance()["__REG_EJPG_H"                    ])
#define REG_EJPG_HT                               (DisplaySettings::getInstance()["__REG_EJPG_HT"                   ])
#define REG_EJPG_OPTIONS                          (DisplaySettings::getInstance()["__REG_EJPG_OPTIONS"              ])
#define REG_EJPG_Q                                (DisplaySettings::getInstance()["__REG_EJPG_Q"                    ])
#define REG_EJPG_READY                            (DisplaySettings::getInstance()["__REG_EJPG_READY"                ])
#define REG_EJPG_RI                               (DisplaySettings::getInstance()["__REG_EJPG_RI"                   ])
#define REG_EJPG_SCALE                            (DisplaySettings::getInstance()["__REG_EJPG_SCALE"                ])
#define REG_EJPG_TDA                              (DisplaySettings::getInstance()["__REG_EJPG_TDA"                  ])
#define REG_EJPG_TQ                               (DisplaySettings::getInstance()["__REG_EJPG_TQ"                   ])
#define REG_EJPG_W                                (DisplaySettings::getInstance()["__REG_EJPG_W"                    ])
#define REG_ESPIM_ADD                             (DisplaySettings::getInstance()["__REG_ESPIM_ADD"                 ])
#define REG_ESPIM_COUNT                           (DisplaySettings::getInstance()["__REG_ESPIM_COUNT"               ])
#define REG_ESPIM_DUMMY                           (DisplaySettings::getInstance()["__REG_ESPIM_DUMMY"               ])
#define REG_ESPIM_READSTART                       (DisplaySettings::getInstance()["__REG_ESPIM_READSTART"           ])
#define REG_ESPIM_SEQ                             (DisplaySettings::getInstance()["__REG_ESPIM_SEQ"                 ])
#define REG_ESPIM_TRIG                            (DisplaySettings::getInstance()["__REG_ESPIM_TRIG"                ])
#define REG_ESPIM_WINDOW                          (DisplaySettings::getInstance()["__REG_ESPIM_WINDOW"              ])
#define REG_FLASH_SIZE                            (DisplaySettings::getInstance()["__REG_FLASH_SIZE"                ])
#define REG_FLASH_STATUS                          (DisplaySettings::getInstance()["__REG_FLASH_STATUS"              ])
#define REG_FRAMES                                (DisplaySettings::getInstance()["__REG_FRAMES"                    ])
#define REG_FREQUENCY                             (DisplaySettings::getInstance()["__REG_FREQUENCY"                 ])
#define REG_FULLBUSYBITS                          (DisplaySettings::getInstance()["__REG_FULLBUSYBITS"              ])
#define REG_GPIO                                  (DisplaySettings::getInstance()["__REG_GPIO"                      ])
#define REG_GPIOX                                 (DisplaySettings::getInstance()["__REG_GPIOX"                     ])
#define REG_GPIOX_DIR                             (DisplaySettings::getInstance()["__REG_GPIOX_DIR"                 ])
#define REG_GPIO_DIR                              (DisplaySettings::getInstance()["__REG_GPIO_DIR"                  ])
#define REG_HCYCLE                                (DisplaySettings::getInstance()["__REG_HCYCLE"                    ])
#define REG_HOFFSET                               (DisplaySettings::getInstance()["__REG_HOFFSET"                   ])
#define REG_HSIZE                                 (DisplaySettings::getInstance()["__REG_HSIZE"                     ])
#define REG_HSYNC0                                (DisplaySettings::getInstance()["__REG_HSYNC0"                    ])
#define REG_HSYNC1                                (DisplaySettings::getInstance()["__REG_HSYNC1"                    ])
#define REG_ID                                    (DisplaySettings::getInstance()["__REG_ID"                        ])
#define REG_INT_EN                                (DisplaySettings::getInstance()["__REG_INT_EN"                    ])
#define REG_INT_FLAGS                             (DisplaySettings::getInstance()["__REG_INT_FLAGS"                 ])
#define REG_INT_MASK                              (DisplaySettings::getInstance()["__REG_INT_MASK"                  ])
#define REG_J1_COLD                               (DisplaySettings::getInstance()["__REG_J1_COLD"                   ])
#define REG_J1_INT                                (DisplaySettings::getInstance()["__REG_J1_INT"                    ])
#define REG_MACRO_0                               (DisplaySettings::getInstance()["__REG_MACRO_0"                   ])
#define REG_MACRO_1                               (DisplaySettings::getInstance()["__REG_MACRO_1"                   ])
#define REG_MEDIAFIFO_BASE                        (DisplaySettings::getInstance()["__REG_MEDIAFIFO_BASE"            ])
#define REG_MEDIAFIFO_READ                        (DisplaySettings::getInstance()["__REG_MEDIAFIFO_READ"            ])
#define REG_MEDIAFIFO_SIZE                        (DisplaySettings::getInstance()["__REG_MEDIAFIFO_SIZE"            ])
#define REG_MEDIAFIFO_WRITE                       (DisplaySettings::getInstance()["__REG_MEDIAFIFO_WRITE"           ])
#define REG_OUTBITS                               (DisplaySettings::getInstance()["__REG_OUTBITS"                   ])
#define REG_PATCHED_ANALOG                        (DisplaySettings::getInstance()["__REG_PATCHED_ANALOG"            ])
#define REG_PATCHED_TOUCH_FAULT                   (DisplaySettings::getInstance()["__REG_PATCHED_TOUCH_FAULT"       ])
#define REG_PCLK                                  (DisplaySettings::getInstance()["__REG_PCLK"                      ])
#define REG_PCLK_POL                              (DisplaySettings::getInstance()["__REG_PCLK_POL"                  ])
#define REG_PLAY                                  (DisplaySettings::getInstance()["__REG_PLAY"                      ])
#define REG_PLAYBACK_FORMAT                       (DisplaySettings::getInstance()["__REG_PLAYBACK_FORMAT"           ])
#define REG_PLAYBACK_FREQ                         (DisplaySettings::getInstance()["__REG_PLAYBACK_FREQ"             ])
#define REG_PLAYBACK_LENGTH                       (DisplaySettings::getInstance()["__REG_PLAYBACK_LENGTH"           ])
#define REG_PLAYBACK_LOOP                         (DisplaySettings::getInstance()["__REG_PLAYBACK_LOOP"             ])
#define REG_PLAYBACK_PAUSE                        (DisplaySettings::getInstance()["__REG_PLAYBACK_PAUSE"            ])
#define REG_PLAYBACK_PLAY                         (DisplaySettings::getInstance()["__REG_PLAYBACK_PLAY"             ])
#define REG_PLAYBACK_READPTR                      (DisplaySettings::getInstance()["__REG_PLAYBACK_READPTR"          ])
#define REG_PLAYBACK_START                        (DisplaySettings::getInstance()["__REG_PLAYBACK_START"            ])
#define REG_PLAY_CONTROL                          (DisplaySettings::getInstance()["__REG_PLAY_CONTROL"              ])
#define REG_PWM_DUTY                              (DisplaySettings::getInstance()["__REG_PWM_DUTY"                  ])
#define REG_PWM_HZ                                (DisplaySettings::getInstance()["__REG_PWM_HZ"                    ])
#define REG_RAM_FOLD                              (DisplaySettings::getInstance()["__REG_RAM_FOLD"                  ])
#define REG_RASTERY                               (DisplaySettings::getInstance()["__REG_RASTERY"                   ])
#define REG_RENDERMODE                            (DisplaySettings::getInstance()["__REG_RENDERMODE"                ])
#define REG_ROMSUB_SEL                            (DisplaySettings::getInstance()["__REG_ROMSUB_SEL"                ])
#define REG_ROTATE                                (DisplaySettings::getInstance()["__REG_ROTATE"                    ])
#define REG_SHA1KEY                               (DisplaySettings::getInstance()["__REG_SHA1KEY"                   ])
#define REG_SNAPFORMAT                            (DisplaySettings::getInstance()["__REG_SNAPFORMAT"                ])
#define REG_SNAPSHOT                              (DisplaySettings::getInstance()["__REG_SNAPSHOT"                  ])
#define REG_SNAPY                                 (DisplaySettings::getInstance()["__REG_SNAPY"                     ])
#define REG_SOUND                                 (DisplaySettings::getInstance()["__REG_SOUND"                     ])
#define REG_SPIM                                  (DisplaySettings::getInstance()["__REG_SPIM"                      ])
#define REG_SPIM_DIR                              (DisplaySettings::getInstance()["__REG_SPIM_DIR"                  ])
#define REG_SPI_EARLY_TX                          (DisplaySettings::getInstance()["__REG_SPI_EARLY_TX"              ])
#define REG_SPI_WIDTH                             (DisplaySettings::getInstance()["__REG_SPI_WIDTH"                 ])
#define REG_SWIZZLE                               (DisplaySettings::getInstance()["__REG_SWIZZLE"                   ])
#define REG_TAG                                   (DisplaySettings::getInstance()["__REG_TAG"                       ])
#define REG_TAG_X                                 (DisplaySettings::getInstance()["__REG_TAG_X"                     ])
#define REG_TAG_Y                                 (DisplaySettings::getInstance()["__REG_TAG_Y"                     ])
#define REG_TAP_CRC                               (DisplaySettings::getInstance()["__REG_TAP_CRC"                   ])
#define REG_TAP_MASK                              (DisplaySettings::getInstance()["__REG_TAP_MASK"                  ])
#define REG_TOUCH_ADC_MODE                        (DisplaySettings::getInstance()["__REG_TOUCH_ADC_MODE"            ])
#define REG_TOUCH_CHARGE                          (DisplaySettings::getInstance()["__REG_TOUCH_CHARGE"              ])
#define REG_TOUCH_DIRECT_XY                       (DisplaySettings::getInstance()["__REG_TOUCH_DIRECT_XY"           ])
#define REG_TOUCH_DIRECT_Z1Z2                     (DisplaySettings::getInstance()["__REG_TOUCH_DIRECT_Z1Z2"         ])
#define REG_TOUCH_FAULT                           (DisplaySettings::getInstance()["__REG_TOUCH_FAULT"               ])
#define REG_TOUCH_MODE                            (DisplaySettings::getInstance()["__REG_TOUCH_MODE"                ])
#define REG_TOUCH_OVERSAMPLE                      (DisplaySettings::getInstance()["__REG_TOUCH_OVERSAMPLE"          ])
#define REG_TOUCH_RAW_XY                          (DisplaySettings::getInstance()["__REG_TOUCH_RAW_XY"              ])
#define REG_TOUCH_RZ                              (DisplaySettings::getInstance()["__REG_TOUCH_RZ"                  ])
#define REG_TOUCH_RZTHRESH                        (DisplaySettings::getInstance()["__REG_TOUCH_RZTHRESH"            ])
#define REG_TOUCH_SCREEN_XY                       (DisplaySettings::getInstance()["__REG_TOUCH_SCREEN_XY"           ])
#define REG_TOUCH_SETTLE                          (DisplaySettings::getInstance()["__REG_TOUCH_SETTLE"              ])
#define REG_TOUCH_TAG                             (DisplaySettings::getInstance()["__REG_TOUCH_TAG"                 ])
#define REG_TOUCH_TAG1                            (DisplaySettings::getInstance()["__REG_TOUCH_TAG1"                ])
#define REG_TOUCH_TAG1_XY                         (DisplaySettings::getInstance()["__REG_TOUCH_TAG1_XY"             ])
#define REG_TOUCH_TAG2                            (DisplaySettings::getInstance()["__REG_TOUCH_TAG2"                ])
#define REG_TOUCH_TAG2_XY                         (DisplaySettings::getInstance()["__REG_TOUCH_TAG2_XY"             ])
#define REG_TOUCH_TAG3                            (DisplaySettings::getInstance()["__REG_TOUCH_TAG3"                ])
#define REG_TOUCH_TAG3_XY                         (DisplaySettings::getInstance()["__REG_TOUCH_TAG3_XY"             ])
#define REG_TOUCH_TAG4                            (DisplaySettings::getInstance()["__REG_TOUCH_TAG4"                ])
#define REG_TOUCH_TAG4_XY                         (DisplaySettings::getInstance()["__REG_TOUCH_TAG4_XY"             ])
#define REG_TOUCH_TAG_XY                          (DisplaySettings::getInstance()["__REG_TOUCH_TAG_XY"              ])
#define REG_TOUCH_TRANSFORM_A                     (DisplaySettings::getInstance()["__REG_TOUCH_TRANSFORM_A"         ])
#define REG_TOUCH_TRANSFORM_B                     (DisplaySettings::getInstance()["__REG_TOUCH_TRANSFORM_B"         ])
#define REG_TOUCH_TRANSFORM_C                     (DisplaySettings::getInstance()["__REG_TOUCH_TRANSFORM_C"         ])
#define REG_TOUCH_TRANSFORM_D                     (DisplaySettings::getInstance()["__REG_TOUCH_TRANSFORM_D"         ])
#define REG_TOUCH_TRANSFORM_E                     (DisplaySettings::getInstance()["__REG_TOUCH_TRANSFORM_E"         ])
#define REG_TOUCH_TRANSFORM_F                     (DisplaySettings::getInstance()["__REG_TOUCH_TRANSFORM_F"         ])
#define REG_TRACKER                               (DisplaySettings::getInstance()["__REG_TRACKER"                   ])
#define REG_TRACKER_1                             (DisplaySettings::getInstance()["__REG_TRACKER_1"                 ])
#define REG_TRACKER_2                             (DisplaySettings::getInstance()["__REG_TRACKER_2"                 ])
#define REG_TRACKER_3                             (DisplaySettings::getInstance()["__REG_TRACKER_3"                 ])
#define REG_TRACKER_4                             (DisplaySettings::getInstance()["__REG_TRACKER_4"                 ])
#define REG_TRIM                                  (DisplaySettings::getInstance()["__REG_TRIM"                      ])
#define REG_VCYCLE                                (DisplaySettings::getInstance()["__REG_VCYCLE"                    ])
#define REG_VOFFSET                               (DisplaySettings::getInstance()["__REG_VOFFSET"                   ])
#define REG_VOL_PB                                (DisplaySettings::getInstance()["__REG_VOL_PB"                    ])
#define REG_VOL_SOUND                             (DisplaySettings::getInstance()["__REG_VOL_SOUND"                 ])
#define REG_VSIZE                                 (DisplaySettings::getInstance()["__REG_VSIZE"                     ])
#define REG_VSYNC0                                (DisplaySettings::getInstance()["__REG_VSYNC0"                    ])
#define REG_VSYNC1                                (DisplaySettings::getInstance()["__REG_VSYNC1"                    ])
#define REPEAT                                    (DisplaySettings::getInstance()["__REPEAT"                        ])
#define REPLACE                                   (DisplaySettings::getInstance()["__REPLACE"                       ])
#define RGB332                                    (DisplaySettings::getInstance()["__RGB332"                        ])
#define RGB565                                    (DisplaySettings::getInstance()["__RGB565"                        ])
#define SRC_ALPHA                                 (DisplaySettings::getInstance()["__SRC_ALPHA"                     ])
#define SS_A0                                     (DisplaySettings::getInstance()["__SS_A0"                         ])
#define SS_A1                                     (DisplaySettings::getInstance()["__SS_A1"                         ])
#define SS_A2                                     (DisplaySettings::getInstance()["__SS_A2"                         ])
#define SS_A3                                     (DisplaySettings::getInstance()["__SS_A3"                         ])
#define SS_A4                                     (DisplaySettings::getInstance()["__SS_A4"                         ])
#define SS_A5                                     (DisplaySettings::getInstance()["__SS_A5"                         ])
#define SS_A6                                     (DisplaySettings::getInstance()["__SS_A6"                         ])
#define SS_A7                                     (DisplaySettings::getInstance()["__SS_A7"                         ])
#define SS_PAUSE                                  (DisplaySettings::getInstance()["__SS_PAUSE"                      ])
#define SS_Q0                                     (DisplaySettings::getInstance()["__SS_Q0"                         ])
#define SS_Q1                                     (DisplaySettings::getInstance()["__SS_Q1"                         ])
#define SS_Q2                                     (DisplaySettings::getInstance()["__SS_Q2"                         ])
#define SS_Q3                                     (DisplaySettings::getInstance()["__SS_Q3"                         ])
#define SS_Q4                                     (DisplaySettings::getInstance()["__SS_Q4"                         ])
#define SS_Q5                                     (DisplaySettings::getInstance()["__SS_Q5"                         ])
#define SS_Q6                                     (DisplaySettings::getInstance()["__SS_Q6"                         ])
#define SS_Q7                                     (DisplaySettings::getInstance()["__SS_Q7"                         ])
#define SS_Q8                                     (DisplaySettings::getInstance()["__SS_Q8"                         ])
#define SS_Q9                                     (DisplaySettings::getInstance()["__SS_Q9"                         ])
#define SS_QA                                     (DisplaySettings::getInstance()["__SS_QA"                         ])
#define SS_QB                                     (DisplaySettings::getInstance()["__SS_QB"                         ])
#define SS_QC                                     (DisplaySettings::getInstance()["__SS_QC"                         ])
#define SS_QD                                     (DisplaySettings::getInstance()["__SS_QD"                         ])
#define SS_QE                                     (DisplaySettings::getInstance()["__SS_QE"                         ])
#define SS_QF                                     (DisplaySettings::getInstance()["__SS_QF"                         ])
#define SS_QI                                     (DisplaySettings::getInstance()["__SS_QI"                         ])
#define SS_S0                                     (DisplaySettings::getInstance()["__SS_S0"                         ])
#define SS_S1                                     (DisplaySettings::getInstance()["__SS_S1"                         ])
#define TEXT8X8                                   (DisplaySettings::getInstance()["__TEXT8X8"                       ])
#define TEXTVGA                                   (DisplaySettings::getInstance()["__TEXTVGA"                       ])
#define TOUCHMODE_CONTINUOUS                      (DisplaySettings::getInstance()["__TOUCHMODE_CONTINUOUS"          ])
#define TOUCHMODE_FRAME                           (DisplaySettings::getInstance()["__TOUCHMODE_FRAME"               ])
#define TOUCHMODE_OFF                             (DisplaySettings::getInstance()["__TOUCHMODE_OFF"                 ])
#define TOUCHMODE_ONESHOT                         (DisplaySettings::getInstance()["__TOUCHMODE_ONESHOT"             ])
#define ULAW_SAMPLES                              (DisplaySettings::getInstance()["__ULAW_SAMPLES"                  ])
#define ZERO                                      (DisplaySettings::getInstance()["__ZERO"                          ])

#define RAM_ERR_REPORT                            (DisplaySettings::getInstance()["__RAM_ERR_REPORT"                ])
#define ROMFONT_TABLEADDRESS                      (DisplaySettings::getInstance()["__ROMFONT_TABLEADDRESS"          ])
#define REG_CTOUCH_TOUCH1_XY                      (DisplaySettings::getInstance()["__REG_CTOUCH_TOUCH1_XY"          ])
#define REG_CTOUCH_TOUCH2_XY                      (DisplaySettings::getInstance()["__REG_CTOUCH_TOUCH2_XY"          ])
#define REG_CTOUCH_TOUCH3_XY                      (DisplaySettings::getInstance()["__REG_CTOUCH_TOUCH3_XY"          ])

//EVE1
#define CMD_CSKETCH                               (DisplaySettings::getInstance()["__CMD_CSKETCH"                    ])
#define CMD_IDCT                                  (DisplaySettings::getInstance()["__CMD_IDCT"                       ])
#define DECR_WRAP                                 (DisplaySettings::getInstance()["__DECR_WRAP"                      ])
#define INCR_WRAP                                 (DisplaySettings::getInstance()["__INCR_WRAP"                      ])
#define RAM_PAL                                   (DisplaySettings::getInstance()["__RAM_PAL"                        ])
#define REG_CTOUCH_GESTURE                        (DisplaySettings::getInstance()["__REG_CTOUCH_GESTURE"             ])
#define REG_CTOUCH_IDS                            (DisplaySettings::getInstance()["__REG_CTOUCH_IDS"                 ])

//EVE2

#endif // DISPLAYSETTINGS_H
