#include "displaysettings.h"

#include <QDebug>
#include <cassert>
#include "platform.h"
#include "Gpu.h"

DisplaySettings::DisplaySettings()
{
    setDisplaySize(ds43);
    setDisplayGeneration(dgEve1);
}

QString DisplaySettings::displaySizeToString(DisplaySettings::DisplaySize ds)
{
    switch (ds) {
    case DisplaySettings::ds35:
        return "Size_35";
    case DisplaySettings::ds43:
        return "Size_43";
    case DisplaySettings::ds50:
        return "Size_50";
    case DisplaySettings::ds70:
        return "Size_70";
    }
    return QString();
}

QString DisplaySettings::displayGenerationToString(DisplaySettings::DisplayGeneration dg)
{
    switch (dg){
    case DisplaySettings::dgEve1:
        return "EVE_1";
    case DisplaySettings::dgEve2:
        return "EVE_2";
    case DisplaySettings::dgEve3:
        return "EVE_3";
    }
}

DisplaySettings::DisplayGeneration DisplaySettings::getDisplayGeneration() const
{
    return mDisplayGeneration;
}

void DisplaySettings::setDisplayGeneration(const DisplaySettings::DisplayGeneration &disGen)
{
    mDisplayGeneration = disGen;
    switch (disGen) {
    case DisplaySettings::dgEve1:
        mapDisplayOptions["__LOW_FREQ_BOUND"                 ] = 47040000L   ;

        mapDisplayOptions["__RAM_G_SIZE"                     ] = 256*1024L   ;
        mapDisplayOptions["__ADC_DIFFERENTIAL"               ] = 1UL         ;
        mapDisplayOptions["__ADC_SINGLE_ENDED"               ] = 0UL         ;
        mapDisplayOptions["__ADPCM_SAMPLES"                  ] = 2UL         ;
        mapDisplayOptions["__ALWAYS"                         ] = 7UL         ;
        mapDisplayOptions["__ARGB1555"                       ] = 0UL         ;
        mapDisplayOptions["__ARGB2"                          ] = 5UL         ;
        mapDisplayOptions["__ARGB4"                          ] = 6UL         ;
        mapDisplayOptions["__BARGRAPH"                       ] = 11UL        ;
        mapDisplayOptions["__BILINEAR"                       ] = 1UL         ;
        mapDisplayOptions["__BITMAPS"                        ] = 1UL         ;
        mapDisplayOptions["__BORDER"                         ] = 0UL         ;

        mapDisplayOptions["__CMDBUF_SIZE"                    ] = 4096UL      ;
        mapDisplayOptions["__CMD_APPEND"                     ] = 4294967070UL;
        mapDisplayOptions["__CMD_BGCOLOR"                    ] = 4294967049UL;
        mapDisplayOptions["__CMD_BITMAP_TRANSFORM"           ] = 4294967073UL;
        mapDisplayOptions["__CMD_BUTTON"                     ] = 4294967053UL;
        mapDisplayOptions["__CMD_CALIBRATE"                  ] = 4294967061UL;
        mapDisplayOptions["__CMD_CSKETCH"                    ] = 4294967093UL;
        mapDisplayOptions["__CMD_CLOCK"                      ] = 4294967060UL;
        mapDisplayOptions["__CMD_COLDSTART"                  ] = 4294967090UL;
        mapDisplayOptions["__CMD_CRC"                        ] = 4294967043UL;
        mapDisplayOptions["__CMD_DIAL"                       ] = 4294967085UL;
        mapDisplayOptions["__CMD_DLSTART"                    ] = 4294967040UL;
        mapDisplayOptions["__CMD_EXECUTE"                    ] = 4294967047UL;
        mapDisplayOptions["__CMD_FGCOLOR"                    ] = 4294967050UL;
        mapDisplayOptions["__CMD_GAUGE"                      ] = 4294967059UL;
        mapDisplayOptions["__CMD_GETMATRIX"                  ] = 4294967091UL;
        mapDisplayOptions["__CMD_GETPOINT"                   ] = 4294967048UL;
        mapDisplayOptions["__CMD_GETPROPS"                   ] = 4294967077UL;
        mapDisplayOptions["__CMD_GETPTR"                     ] = 4294967075UL;
        mapDisplayOptions["__CMD_GRADCOLOR"                  ] = 4294967092UL;
        mapDisplayOptions["__CMD_GRADIENT"                   ] = 4294967051UL;
        mapDisplayOptions["__CMD_HAMMERAUX"                  ] = 4294967044UL;
        mapDisplayOptions["__CMD_IDCT"                       ] = 4294967046UL;
        mapDisplayOptions["__CMD_INFLATE"                    ] = 4294967074UL;
        mapDisplayOptions["__CMD_INTERRUPT"                  ] = 4294967042UL;
        mapDisplayOptions["__CMD_KEYS"                       ] = 4294967054UL;
        mapDisplayOptions["__CMD_LOADIDENTITY"               ] = 4294967078UL;
        mapDisplayOptions["__CMD_LOADIMAGE"                  ] = 4294967076UL;
        mapDisplayOptions["__CMD_LOGO"                       ] = 4294967089UL;
        mapDisplayOptions["__CMD_MARCH"                      ] = 4294967045UL;
        mapDisplayOptions["__CMD_MEMCPY"                     ] = 4294967069UL;
        mapDisplayOptions["__CMD_MEMCRC"                     ] = 4294967064UL;
        mapDisplayOptions["__CMD_MEMSET"                     ] = 4294967067UL;
        mapDisplayOptions["__CMD_MEMWRITE"                   ] = 4294967066UL;
        mapDisplayOptions["__CMD_MEMZERO"                    ] = 4294967068UL;
        mapDisplayOptions["__CMD_NUMBER"                     ] = 4294967086UL;
        mapDisplayOptions["__CMD_PROGRESS"                   ] = 4294967055UL;
        mapDisplayOptions["__CMD_REGREAD"                    ] = 4294967065UL;
        mapDisplayOptions["__CMD_ROTATE"                     ] = 4294967081UL;
        mapDisplayOptions["__CMD_SCALE"                      ] = 4294967080UL;
        mapDisplayOptions["__CMD_SCREENSAVER"                ] = 4294967087UL;
        mapDisplayOptions["__CMD_SCROLLBAR"                  ] = 4294967057UL;
        mapDisplayOptions["__CMD_SETFONT"                    ] = 4294967083UL;
        mapDisplayOptions["__CMD_SETMATRIX"                  ] = 4294967082UL;
        mapDisplayOptions["__CMD_SKETCH"                     ] = 4294967088UL;
        mapDisplayOptions["__CMD_SLIDER"                     ] = 4294967056UL;
        mapDisplayOptions["__CMD_SNAPSHOT"                   ] = 4294967071UL;
        mapDisplayOptions["__CMD_SPINNER"                    ] = 4294967062UL;
        mapDisplayOptions["__CMD_STOP"                       ] = 4294967063UL;
        mapDisplayOptions["__CMD_SWAP"                       ] = 4294967041UL;
        mapDisplayOptions["__CMD_TEXT"                       ] = 4294967052UL;
        mapDisplayOptions["__CMD_TOGGLE"                     ] = 4294967058UL;
        mapDisplayOptions["__CMD_TOUCH_TRANSFORM"            ] = 4294967072UL;
        mapDisplayOptions["__CMD_TRACK"                      ] = 4294967084UL;
        mapDisplayOptions["__CMD_TRANSLATE"                  ] = 4294967079UL;

        mapDisplayOptions["__DECR"                           ] = 4UL         ;
        mapDisplayOptions["__DECR_WRAP"                      ] = 7UL         ;
        mapDisplayOptions["__DLSWAP_DONE"                    ] = 0UL         ;
        mapDisplayOptions["__DLSWAP_FRAME"                   ] = 2UL         ;
        mapDisplayOptions["__DLSWAP_LINE"                    ] = 1UL         ;
        mapDisplayOptions["__DST_ALPHA"                      ] = 3UL         ;
        mapDisplayOptions["__EDGE_STRIP_A"                   ] = 7UL         ;
        mapDisplayOptions["__EDGE_STRIP_B"                   ] = 8UL         ;
        mapDisplayOptions["__EDGE_STRIP_L"                   ] = 6UL         ;
        mapDisplayOptions["__EDGE_STRIP_R"                   ] = 5UL         ;
        mapDisplayOptions["__EQUAL"                          ] = 5UL         ;
        mapDisplayOptions["__GEQUAL"                         ] = 4UL         ;
        mapDisplayOptions["__GREATER"                        ] = 3UL         ;
        mapDisplayOptions["__INCR"                           ] = 3UL         ;
        mapDisplayOptions["__INCR_WRAP"                      ] = 6UL         ;
        mapDisplayOptions["__INT_CMDEMPTY"                   ] = 32UL        ;
        mapDisplayOptions["__INT_CMDFLAG"                    ] = 64UL        ;
        mapDisplayOptions["__INT_CONVCOMPLETE"               ] = 128UL       ;
        mapDisplayOptions["__INT_PLAYBACK"                   ] = 16UL        ;
        mapDisplayOptions["__INT_SOUND"                      ] = 8UL         ;
        mapDisplayOptions["__INT_SWAP"                       ] = 1UL         ;
        mapDisplayOptions["__INT_TAG"                        ] = 4UL         ;
        mapDisplayOptions["__INT_TOUCH"                      ] = 2UL         ;
        mapDisplayOptions["__INVERT"                         ] = 5UL         ;

        mapDisplayOptions["__KEEP"                           ] = 1UL         ;
        mapDisplayOptions["__L1"                             ] = 1UL         ;
        mapDisplayOptions["__L4"                             ] = 2UL         ;
        mapDisplayOptions["__L8"                             ] = 3UL         ;
        mapDisplayOptions["__LEQUAL"                         ] = 2UL         ;
        mapDisplayOptions["__LESS"                           ] = 1UL         ;
        mapDisplayOptions["__LINEAR_SAMPLES"                 ] = 0UL         ;
        mapDisplayOptions["__LINES"                          ] = 3UL         ;
        mapDisplayOptions["__LINE_STRIP"                     ] = 4UL         ;
        mapDisplayOptions["__NEAREST"                        ] = 0UL         ;
        mapDisplayOptions["__NEVER"                          ] = 0UL         ;
        mapDisplayOptions["__NOTEQUAL"                       ] = 6UL         ;
        mapDisplayOptions["__ONE"                            ] = 1UL         ;
        mapDisplayOptions["__ONE_MINUS_DST_ALPHA"            ] = 5UL         ;
        mapDisplayOptions["__ONE_MINUS_SRC_ALPHA"            ] = 4UL         ;
        mapDisplayOptions["__OPT_CENTER"                     ] = 1536UL      ;
        mapDisplayOptions["__OPT_CENTERX"                    ] = 512UL       ;
        mapDisplayOptions["__OPT_CENTERY"                    ] = 1024UL      ;
        mapDisplayOptions["__OPT_FLAT"                       ] = 256UL       ;
        mapDisplayOptions["__OPT_MONO"                       ] = 1UL         ;
        mapDisplayOptions["__OPT_NOBACK"                     ] = 4096UL      ;
        mapDisplayOptions["__OPT_NODL"                       ] = 2UL         ;
        mapDisplayOptions["__OPT_NOHANDS"                    ] = 49152UL     ;
        mapDisplayOptions["__OPT_NOHM"                       ] = 16384UL     ;
        mapDisplayOptions["__OPT_NOPOINTER"                  ] = 16384UL     ;
        mapDisplayOptions["__OPT_NOSECS"                     ] = 32768UL     ;
        mapDisplayOptions["__OPT_NOTICKS"                    ] = 8192UL      ;
        mapDisplayOptions["__OPT_RIGHTX"                     ] = 2048UL      ;
        mapDisplayOptions["__OPT_SIGNED"                     ] = 256UL       ;
        mapDisplayOptions["__PALETTED"                       ] = 8UL         ;
        mapDisplayOptions["__FTPOINTS"                       ] = 2UL         ;
        mapDisplayOptions["__RECTS"                          ] = 9UL         ;

        mapDisplayOptions["__RAM_CMD"                        ] = 1081344UL   ;
        mapDisplayOptions["__RAM_DL"                         ] = 1048576UL   ;
        mapDisplayOptions["__RAM_G"                          ] = 0UL         ;
        mapDisplayOptions["__RAM_PAL"                        ] = 1056768UL   ;
        mapDisplayOptions["__RAM_REG"                        ] = 1057792UL   ;

        mapDisplayOptions["__ROMFONT_TABLEADDRESS"           ] = 1048572UL   ;

        mapDisplayOptions["__REG_ANALOG"                     ] = 1058104UL   ;
        mapDisplayOptions["__REG_ANA_COMP"                   ] = 1058160UL   ;
        mapDisplayOptions["__REG_CLOCK"                      ] = 1057800UL   ;
        mapDisplayOptions["__REG_CMD_DL"                     ] = 1058028UL   ;
        mapDisplayOptions["__REG_CMD_READ"                   ] = 1058020UL   ;
        mapDisplayOptions["__REG_CMD_WRITE"                  ] = 1058024UL   ;
        mapDisplayOptions["__REG_CPURESET"                   ] = 1057820UL   ;
        mapDisplayOptions["__REG_CRC"                        ] = 1058152UL   ;
        mapDisplayOptions["__REG_CSPREAD"                    ] = 1057892UL   ;
        mapDisplayOptions["__REG_CYA0"                       ] = 1058000UL   ;
        mapDisplayOptions["__REG_CYA1"                       ] = 1058004UL   ;
        mapDisplayOptions["__REG_CYA_TOUCH"                  ] = 1058100UL   ;
        mapDisplayOptions["__REG_DATESTAMP"                  ] = 1058108UL   ;
        mapDisplayOptions["__REG_DITHER"                     ] = 1057884UL   ;
        mapDisplayOptions["__REG_DLSWAP"                     ] = 1057872UL   ;
        mapDisplayOptions["__REG_FRAMES"                     ] = 1057796UL   ;
        mapDisplayOptions["__REG_FREQUENCY"                  ] = 1057804UL   ;
        mapDisplayOptions["__REG_GPIO"                       ] = 1057936UL   ;
        mapDisplayOptions["__REG_GPIO_DIR"                   ] = 1057932UL   ;
        mapDisplayOptions["__REG_HCYCLE"                     ] = 1057832UL   ;
        mapDisplayOptions["__REG_HOFFSET"                    ] = 1057836UL   ;
        mapDisplayOptions["__REG_HSIZE"                      ] = 1057840UL   ;
        mapDisplayOptions["__REG_HSYNC0"                     ] = 1057844UL   ;
        mapDisplayOptions["__REG_HSYNC1"                     ] = 1057848UL   ;
        mapDisplayOptions["__REG_ID"                         ] = 1057792UL   ;
        mapDisplayOptions["__REG_INT_EN"                     ] = 1057948UL   ;
        mapDisplayOptions["__REG_INT_FLAGS"                  ] = 1057944UL   ;
        mapDisplayOptions["__REG_INT_MASK"                   ] = 1057952UL   ;
        mapDisplayOptions["__REG_MACRO_0"                    ] = 1057992UL   ;
        mapDisplayOptions["__REG_MACRO_1"                    ] = 1057996UL   ;
        mapDisplayOptions["__REG_OUTBITS"                    ] = 1057880UL   ;
        mapDisplayOptions["__REG_PCLK"                       ] = 1057900UL   ;
        mapDisplayOptions["__REG_PCLK_POL"                   ] = 1057896UL   ;
        mapDisplayOptions["__REG_PLAY"                       ] = 1057928UL   ;
        mapDisplayOptions["__REG_PLAYBACK_FORMAT"            ] = 1057972UL   ;
        mapDisplayOptions["__REG_PLAYBACK_FREQ"              ] = 1057968UL   ;
        mapDisplayOptions["__REG_PLAYBACK_LENGTH"            ] = 1057960UL   ;
        mapDisplayOptions["__REG_PLAYBACK_LOOP"              ] = 1057976UL   ;
        mapDisplayOptions["__REG_PLAYBACK_PLAY"              ] = 1057980UL   ;
        mapDisplayOptions["__REG_PLAYBACK_READPTR"           ] = 1057964UL   ;
        mapDisplayOptions["__REG_PLAYBACK_START"             ] = 1057956UL   ;
        mapDisplayOptions["__REG_PWM_DUTY"                   ] = 1057988UL   ;
        mapDisplayOptions["__REG_PWM_HZ"                     ] = 1057984UL   ;
        mapDisplayOptions["__REG_RENDERMODE"                 ] = 1057808UL   ;
        mapDisplayOptions["__REG_ROMSUB_SEL"                 ] = 1058016UL   ;
        mapDisplayOptions["__REG_ROTATE"                     ] = 1057876UL   ;
        mapDisplayOptions["__REG_SNAPSHOT"                   ] = 1057816UL   ;
        mapDisplayOptions["__REG_SNAPY"                      ] = 1057812UL   ;
        mapDisplayOptions["__REG_SOUND"                      ] = 1057924UL   ;
        mapDisplayOptions["__REG_SWIZZLE"                    ] = 1057888UL   ;
        mapDisplayOptions["__REG_TAG"                        ] = 1057912UL   ;
        mapDisplayOptions["__REG_TAG_X"                      ] = 1057904UL   ;
        mapDisplayOptions["__REG_TAG_Y"                      ] = 1057908UL   ;
        mapDisplayOptions["__REG_TAP_CRC"                    ] = 1057824UL   ;
        mapDisplayOptions["__REG_TAP_MASK"                   ] = 1057828UL   ;
        mapDisplayOptions["__REG_TOUCH_ADC_MODE"             ] = 1058036UL   ;
        mapDisplayOptions["__REG_TOUCH_CHARGE"               ] = 1058040UL   ;
        mapDisplayOptions["__REG_TOUCH_DIRECT_XY"            ] = 1058164UL   ;
        mapDisplayOptions["__REG_TOUCH_DIRECT_Z1Z2"          ] = 1058168UL   ;
        mapDisplayOptions["__REG_TOUCH_MODE"                 ] = 1058032UL   ;
        mapDisplayOptions["__REG_TOUCH_OVERSAMPLE"           ] = 1058048UL   ;
        mapDisplayOptions["__REG_TOUCH_RAW_XY"               ] = 1058056UL   ;
        mapDisplayOptions["__REG_TOUCH_RZ"                   ] = 1058060UL   ;
        mapDisplayOptions["__REG_TOUCH_RZTHRESH"             ] = 1058052UL   ;
        mapDisplayOptions["__REG_TOUCH_SCREEN_XY"            ] = 1058064UL   ;
        mapDisplayOptions["__REG_TOUCH_SETTLE"               ] = 1058044UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG"                  ] = 1058072UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG_XY"               ] = 1058068UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_A"          ] = 1058076UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_B"          ] = 1058080UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_C"          ] = 1058084UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_D"          ] = 1058088UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_E"          ] = 1058092UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_F"          ] = 1058096UL   ;
        mapDisplayOptions["__REG_TRACKER"                    ] = 1085440UL   ;
        mapDisplayOptions["__REG_TRIM"                       ] = 1058156UL   ;
        mapDisplayOptions["__REG_VCYCLE"                     ] = 1057852UL   ;
        mapDisplayOptions["__REG_VOFFSET"                    ] = 1057856UL   ;
        mapDisplayOptions["__REG_VOL_PB"                     ] = 1057916UL   ;
        mapDisplayOptions["__REG_VOL_SOUND"                  ] = 1057920UL   ;
        mapDisplayOptions["__REG_VSIZE"                      ] = 1057860UL   ;
        mapDisplayOptions["__REG_VSYNC0"                     ] = 1057864UL   ;
        mapDisplayOptions["__REG_VSYNC1"                     ] = 1057868UL   ;

        mapDisplayOptions["__REG_CTOUCH_EXTENDED"            ] = 1058036UL   ;
        mapDisplayOptions["__REG_CTOUCH_GESTURE"             ] = 1058104UL   ;
        mapDisplayOptions["__REG_CTOUCH_IDS"                 ] = 1058060UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH0_XY"           ] = 1058064UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH1_XY"           ] = 1058056UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH2_XY"           ] = 1058164UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH3_XY"           ] = 1058168UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH4_X"            ] = 1058104UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH4_Y"            ] = 1058060UL   ;

        mapDisplayOptions["__REPEAT"                         ] = 1UL         ;
        mapDisplayOptions["__REPLACE"                        ] = 2UL         ;
        mapDisplayOptions["__RGB332"                         ] = 4UL         ;
        mapDisplayOptions["__RGB565"                         ] = 7UL         ;
        mapDisplayOptions["__SRC_ALPHA"                      ] = 2UL         ;
        mapDisplayOptions["__TEXT8X8"                        ] = 9UL         ;
        mapDisplayOptions["__TEXTVGA"                        ] = 10UL        ;
        mapDisplayOptions["__TOUCHMODE_CONTINUOUS"           ] = 3UL         ;
        mapDisplayOptions["__TOUCHMODE_FRAME"                ] = 2UL         ;
        mapDisplayOptions["__TOUCHMODE_OFF"                  ] = 0UL         ;
        mapDisplayOptions["__TOUCHMODE_ONESHOT"              ] = 1UL         ;
        mapDisplayOptions["__ULAW_SAMPLES"                   ] = 1UL         ;
        mapDisplayOptions["__ZERO"                           ] = 0UL         ;
        break;
    case DisplaySettings::dgEve2:
        mapDisplayOptions["__LOW_FREQ_BOUND"                 ] = 58800000L   ;
        mapDisplayOptions["__RAM_G_SIZE"                     ] = 1024*1024L  ;

        mapDisplayOptions["__ADC_DIFFERENTIAL"               ] = 1UL         ;
        mapDisplayOptions["__ADC_SINGLE_ENDED"               ] = 0UL         ;
        mapDisplayOptions["__ADPCM_SAMPLES"                  ] = 2UL         ;
        mapDisplayOptions["__ALWAYS"                         ] = 7UL         ;
        mapDisplayOptions["__ARGB1555"                       ] = 0UL         ;
        mapDisplayOptions["__ARGB2"                          ] = 5UL         ;
        mapDisplayOptions["__ARGB4"                          ] = 6UL         ;
        mapDisplayOptions["__BARGRAPH"                       ] = 11UL        ;
        mapDisplayOptions["__BILINEAR"                       ] = 1UL         ;
        mapDisplayOptions["__BITMAPS"                        ] = 1UL         ;
        mapDisplayOptions["__BORDER"                         ] = 0UL         ;
        mapDisplayOptions["__CMDBUF_SIZE"                    ] = 4096UL      ;
        mapDisplayOptions["__CMD_APPEND"                     ] = 4294967070UL;
        mapDisplayOptions["__CMD_BGCOLOR"                    ] = 4294967049UL;
        mapDisplayOptions["__CMD_BITMAP_TRANSFORM"           ] = 4294967073UL;
        mapDisplayOptions["__CMD_BUTTON"                     ] = 4294967053UL;
        mapDisplayOptions["__CMD_CALIBRATE"                  ] = 4294967061UL;
        mapDisplayOptions["__CMD_CLOCK"                      ] = 4294967060UL;
        mapDisplayOptions["__CMD_COLDSTART"                  ] = 4294967090UL;
        mapDisplayOptions["__CMD_CRC"                        ] = 4294967043UL;
        mapDisplayOptions["__CMD_CSKETCH"                    ] = 4294967093UL;
        mapDisplayOptions["__CMD_DIAL"                       ] = 4294967085UL;
        mapDisplayOptions["__CMD_DLSTART"                    ] = 4294967040UL;
        mapDisplayOptions["__CMD_EXECUTE"                    ] = 4294967047UL;
        mapDisplayOptions["__CMD_FGCOLOR"                    ] = 4294967050UL;
        mapDisplayOptions["__CMD_GAUGE"                      ] = 4294967059UL;
        mapDisplayOptions["__CMD_GETMATRIX"                  ] = 4294967091UL;
        mapDisplayOptions["__CMD_GETPOINT"                   ] = 4294967048UL;
        mapDisplayOptions["__CMD_GETPROPS"                   ] = 4294967077UL;
        mapDisplayOptions["__CMD_GETPTR"                     ] = 4294967075UL;
        mapDisplayOptions["__CMD_GRADCOLOR"                  ] = 4294967092UL;
        mapDisplayOptions["__CMD_GRADIENT"                   ] = 4294967051UL;
        mapDisplayOptions["__CMD_HAMMERAUX"                  ] = 4294967044UL;
        mapDisplayOptions["__CMD_IDCT_DELETED"               ] = 4294967046UL;
        mapDisplayOptions["__CMD_INFLATE"                    ] = 4294967074UL;
        mapDisplayOptions["__CMD_INTERRUPT"                  ] = 4294967042UL;
        mapDisplayOptions["__CMD_INT_RAMSHARED"              ] = 4294967101UL;
        mapDisplayOptions["__CMD_INT_SWLOADIMAGE"            ] = 4294967102UL;
        mapDisplayOptions["__CMD_KEYS"                       ] = 4294967054UL;
        mapDisplayOptions["__CMD_LOADIDENTITY"               ] = 4294967078UL;
        mapDisplayOptions["__CMD_LOADIMAGE"                  ] = 4294967076UL;
        mapDisplayOptions["__CMD_LOGO"                       ] = 4294967089UL;
        mapDisplayOptions["__CMD_MARCH"                      ] = 4294967045UL;
        mapDisplayOptions["__CMD_MEDIAFIFO"                  ] = 4294967097UL;
        mapDisplayOptions["__CMD_MEMCPY"                     ] = 4294967069UL;
        mapDisplayOptions["__CMD_MEMCRC"                     ] = 4294967064UL;
        mapDisplayOptions["__CMD_MEMSET"                     ] = 4294967067UL;
        mapDisplayOptions["__CMD_MEMWRITE"                   ] = 4294967066UL;
        mapDisplayOptions["__CMD_MEMZERO"                    ] = 4294967068UL;
        mapDisplayOptions["__CMD_NUMBER"                     ] = 4294967086UL;
        mapDisplayOptions["__CMD_PLAYVIDEO"                  ] = 4294967098UL;
        mapDisplayOptions["__CMD_PROGRESS"                   ] = 4294967055UL;
        mapDisplayOptions["__CMD_REGREAD"                    ] = 4294967065UL;
        mapDisplayOptions["__CMD_ROMFONT"                    ] = 4294967103UL;
        mapDisplayOptions["__CMD_ROTATE"                     ] = 4294967081UL;
        mapDisplayOptions["__CMD_SCALE"                      ] = 4294967080UL;
        mapDisplayOptions["__CMD_SCREENSAVER"                ] = 4294967087UL;
        mapDisplayOptions["__CMD_SCROLLBAR"                  ] = 4294967057UL;
        mapDisplayOptions["__CMD_SETBASE"                    ] = 4294967096UL;
        mapDisplayOptions["__CMD_SETBITMAP"                  ] = 4294967107UL;
        mapDisplayOptions["__CMD_SETFONT"                    ] = 4294967083UL;
        mapDisplayOptions["__CMD_SETFONT2"                   ] = 4294967099UL;
        mapDisplayOptions["__CMD_SETMATRIX"                  ] = 4294967082UL;
        mapDisplayOptions["__CMD_SETROTATE"                  ] = 4294967094UL;
        mapDisplayOptions["__CMD_SETSCRATCH"                 ] = 4294967100UL;
        mapDisplayOptions["__CMD_SKETCH"                     ] = 4294967088UL;
        mapDisplayOptions["__CMD_SLIDER"                     ] = 4294967056UL;
        mapDisplayOptions["__CMD_SNAPSHOT"                   ] = 4294967071UL;
        mapDisplayOptions["__CMD_SNAPSHOT2"                  ] = 4294967095UL;
        mapDisplayOptions["__CMD_SPINNER"                    ] = 4294967062UL;
        mapDisplayOptions["__CMD_STOP"                       ] = 4294967063UL;
        mapDisplayOptions["__CMD_SWAP"                       ] = 4294967041UL;
        mapDisplayOptions["__CMD_SYNC"                       ] = 4294967106UL;
        mapDisplayOptions["__CMD_TEXT"                       ] = 4294967052UL;
        mapDisplayOptions["__CMD_TOGGLE"                     ] = 4294967058UL;
        mapDisplayOptions["__CMD_TOUCH_TRANSFORM"            ] = 4294967072UL;
        mapDisplayOptions["__CMD_TRACK"                      ] = 4294967084UL;
        mapDisplayOptions["__CMD_TRANSLATE"                  ] = 4294967079UL;
        mapDisplayOptions["__CMD_VIDEOFRAME"                 ] = 4294967105UL;
        mapDisplayOptions["__CMD_VIDEOSTART"                 ] = 4294967104UL;
        mapDisplayOptions["__DECR"                           ] = 4UL         ;
        mapDisplayOptions["__DLSWAP_DONE"                    ] = 0UL         ;
        mapDisplayOptions["__DLSWAP_FRAME"                   ] = 2UL         ;
        mapDisplayOptions["__DLSWAP_LINE"                    ] = 1UL         ;
        mapDisplayOptions["__DST_ALPHA"                      ] = 3UL         ;
        mapDisplayOptions["__EDGE_STRIP_A"                   ] = 7UL         ;
        mapDisplayOptions["__EDGE_STRIP_B"                   ] = 8UL         ;
        mapDisplayOptions["__EDGE_STRIP_L"                   ] = 6UL         ;
        mapDisplayOptions["__EDGE_STRIP_R"                   ] = 5UL         ;
        mapDisplayOptions["__EQUAL"                          ] = 5UL         ;
        mapDisplayOptions["__GEQUAL"                         ] = 4UL         ;
        mapDisplayOptions["__GREATER"                        ] = 3UL         ;
        mapDisplayOptions["__INCR"                           ] = 3UL         ;
        mapDisplayOptions["__INT_CMDEMPTY"                   ] = 32UL        ;
        mapDisplayOptions["__INT_CMDFLAG"                    ] = 64UL        ;
        mapDisplayOptions["__INT_CONVCOMPLETE"               ] = 128UL       ;
        mapDisplayOptions["__INT_G8"                         ] = 18UL        ;
        mapDisplayOptions["__INT_L8C"                        ] = 12UL        ;
        mapDisplayOptions["__INT_PLAYBACK"                   ] = 16UL        ;
        mapDisplayOptions["__INT_SOUND"                      ] = 8UL         ;
        mapDisplayOptions["__INT_SWAP"                       ] = 1UL         ;
        mapDisplayOptions["__INT_TAG"                        ] = 4UL         ;
        mapDisplayOptions["__INT_TOUCH"                      ] = 2UL         ;
        mapDisplayOptions["__INT_VGA"                        ] = 13UL        ;
        mapDisplayOptions["__INVERT"                         ] = 5UL         ;
        mapDisplayOptions["__KEEP"                           ] = 1UL         ;
        mapDisplayOptions["__L1"                             ] = 1UL         ;
        mapDisplayOptions["__L2"                             ] = 17UL        ;
        mapDisplayOptions["__L4"                             ] = 2UL         ;
        mapDisplayOptions["__L8"                             ] = 3UL         ;
        mapDisplayOptions["__LEQUAL"                         ] = 2UL         ;
        mapDisplayOptions["__LESS"                           ] = 1UL         ;
        mapDisplayOptions["__LINEAR_SAMPLES"                 ] = 0UL         ;
        mapDisplayOptions["__LINES"                          ] = 3UL         ;
        mapDisplayOptions["__LINE_STRIP"                     ] = 4UL         ;
        mapDisplayOptions["__NEAREST"                        ] = 0UL         ;
        mapDisplayOptions["__NEVER"                          ] = 0UL         ;
        mapDisplayOptions["__NOTEQUAL"                       ] = 6UL         ;
        mapDisplayOptions["__ONE"                            ] = 1UL         ;
        mapDisplayOptions["__ONE_MINUS_DST_ALPHA"            ] = 5UL         ;
        mapDisplayOptions["__ONE_MINUS_SRC_ALPHA"            ] = 4UL         ;
        mapDisplayOptions["__OPT_CENTER"                     ] = 1536UL      ;
        mapDisplayOptions["__OPT_CENTERX"                    ] = 512UL       ;
        mapDisplayOptions["__OPT_CENTERY"                    ] = 1024UL      ;
        mapDisplayOptions["__OPT_FLAT"                       ] = 256UL       ;
        mapDisplayOptions["__OPT_FULLSCREEN"                 ] = 8UL         ;
        mapDisplayOptions["__OPT_MEDIAFIFO"                  ] = 16UL        ;
        mapDisplayOptions["__OPT_MONO"                       ] = 1UL         ;
        mapDisplayOptions["__OPT_NOBACK"                     ] = 4096UL      ;
        mapDisplayOptions["__OPT_NODL"                       ] = 2UL         ;
        mapDisplayOptions["__OPT_NOHANDS"                    ] = 49152UL     ;
        mapDisplayOptions["__OPT_NOHM"                       ] = 16384UL     ;
        mapDisplayOptions["__OPT_NOPOINTER"                  ] = 16384UL     ;
        mapDisplayOptions["__OPT_NOSECS"                     ] = 32768UL     ;
        mapDisplayOptions["__OPT_NOTEAR"                     ] = 4UL         ;
        mapDisplayOptions["__OPT_NOTICKS"                    ] = 8192UL      ;
        mapDisplayOptions["__OPT_RIGHTX"                     ] = 2048UL      ;
        mapDisplayOptions["__OPT_SIGNED"                     ] = 256UL       ;
        mapDisplayOptions["__OPT_SOUND"                      ] = 32UL        ;
        mapDisplayOptions["__PALETTED"                       ] = 8UL         ;
        mapDisplayOptions["__PALETTED4444"                   ] = 15UL        ;
        mapDisplayOptions["__PALETTED565"                    ] = 14UL        ;
        mapDisplayOptions["__PALETTED8"                      ] = 16UL        ;
        mapDisplayOptions["__FTPOINTS"                       ] = 2UL         ;
        mapDisplayOptions["__RAM_CMD"                        ] = 3178496UL   ;
        mapDisplayOptions["__RAM_DL"                         ] = 3145728UL   ;
        mapDisplayOptions["__RAM_G"                          ] = 0UL         ;
        mapDisplayOptions["__RAM_REG"                        ] = 3153920UL   ;
        mapDisplayOptions["__RAM_ROMSUB"                     ] = 3186688UL   ;
        mapDisplayOptions["__RECTS"                          ] = 9UL         ;
        ;
        mapDisplayOptions["__ROMFONT_TABLEADDRESS"           ] = 3145724UL   ;

        mapDisplayOptions["__REG_ANALOG"                     ] = 3154284UL   ;
        mapDisplayOptions["__REG_ANA_COMP"                   ] = 3154308UL   ;
        mapDisplayOptions["__REG_BIST_EN"                    ] = 3154292UL   ;
        mapDisplayOptions["__REG_BUSYBITS"                   ] = 3154152UL   ;
        mapDisplayOptions["__REG_CLOCK"                      ] = 3153928UL   ;
        mapDisplayOptions["__REG_CMDB_SPACE"                 ] = 3155316UL   ;
        mapDisplayOptions["__REG_CMDB_WRITE"                 ] = 3155320UL   ;
        mapDisplayOptions["__REG_CMD_DL"                     ] = 3154176UL   ;
        mapDisplayOptions["__REG_CMD_READ"                   ] = 3154168UL   ;
        mapDisplayOptions["__REG_CMD_WRITE"                  ] = 3154172UL   ;
        mapDisplayOptions["__REG_CPURESET"                   ] = 3153952UL   ;
        mapDisplayOptions["__REG_CRC"                        ] = 3154296UL   ;
        mapDisplayOptions["__REG_CSPREAD"                    ] = 3154024UL   ;
        mapDisplayOptions["__REG_CTOUCH_EXTENDED"            ] = 3154184UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH0_XY"           ] = 3154212UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH4_X"            ] = 3154284UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH4_Y"            ] = 3154208UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH1_XY"           ] = 3154204UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH2_XY"           ] = 3154316UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH3_XY"           ] = 3154320UL   ;
        mapDisplayOptions["__REG_CYA_TOUCH"                  ] = 3154280UL   ;
        mapDisplayOptions["__REG_DATESTAMP"                  ] = 3155300UL   ;
        mapDisplayOptions["__REG_DITHER"                     ] = 3154016UL   ;
        mapDisplayOptions["__REG_DLSWAP"                     ] = 3154004UL   ;
        mapDisplayOptions["__REG_FRAMES"                     ] = 3153924UL   ;
        mapDisplayOptions["__REG_FREQUENCY"                  ] = 3153932UL   ;
        mapDisplayOptions["__REG_GPIO"                       ] = 3154068UL   ;
        mapDisplayOptions["__REG_GPIOX"                      ] = 3154076UL   ;
        mapDisplayOptions["__REG_GPIOX_DIR"                  ] = 3154072UL   ;
        mapDisplayOptions["__REG_GPIO_DIR"                   ] = 3154064UL   ;
        mapDisplayOptions["__REG_HCYCLE"                     ] = 3153964UL   ;
        mapDisplayOptions["__REG_HOFFSET"                    ] = 3153968UL   ;
        mapDisplayOptions["__REG_HSIZE"                      ] = 3153972UL   ;
        mapDisplayOptions["__REG_HSYNC0"                     ] = 3153976UL   ;
        mapDisplayOptions["__REG_HSYNC1"                     ] = 3153980UL   ;
        mapDisplayOptions["__REG_ID"                         ] = 3153920UL   ;
        mapDisplayOptions["__REG_INT_EN"                     ] = 3154092UL   ;
        mapDisplayOptions["__REG_INT_FLAGS"                  ] = 3154088UL   ;
        mapDisplayOptions["__REG_INT_MASK"                   ] = 3154096UL   ;
        mapDisplayOptions["__REG_MACRO_0"                    ] = 3154136UL   ;
        mapDisplayOptions["__REG_MACRO_1"                    ] = 3154140UL   ;
        mapDisplayOptions["__REG_MEDIAFIFO_READ"             ] = 3182612UL   ;
        mapDisplayOptions["__REG_MEDIAFIFO_WRITE"            ] = 3182616UL   ;
        mapDisplayOptions["__REG_OUTBITS"                    ] = 3154012UL   ;
        mapDisplayOptions["__REG_PATCHED_ANALOG"             ] = 3154288UL   ;
        mapDisplayOptions["__REG_PATCHED_TOUCH_FAULT"        ] = 3154284UL   ;
        mapDisplayOptions["__REG_PCLK"                       ] = 3154032UL   ;
        mapDisplayOptions["__REG_PCLK_POL"                   ] = 3154028UL   ;
        mapDisplayOptions["__REG_PLAY"                       ] = 3154060UL   ;
        mapDisplayOptions["__REG_PLAYBACK_FORMAT"            ] = 3154116UL   ;
        mapDisplayOptions["__REG_PLAYBACK_FREQ"              ] = 3154112UL   ;
        mapDisplayOptions["__REG_PLAYBACK_LENGTH"            ] = 3154104UL   ;
        mapDisplayOptions["__REG_PLAYBACK_LOOP"              ] = 3154120UL   ;
        mapDisplayOptions["__REG_PLAYBACK_PLAY"              ] = 3154124UL   ;
        mapDisplayOptions["__REG_PLAYBACK_READPTR"           ] = 3154108UL   ;
        mapDisplayOptions["__REG_PLAYBACK_START"             ] = 3154100UL   ;
        mapDisplayOptions["__REG_PWM_DUTY"                   ] = 3154132UL   ;
        mapDisplayOptions["__REG_PWM_HZ"                     ] = 3154128UL   ;
        mapDisplayOptions["__REG_RENDERMODE"                 ] = 3153936UL   ;
        mapDisplayOptions["__REG_ROMSUB_SEL"                 ] = 3154160UL   ;
        mapDisplayOptions["__REG_ROTATE"                     ] = 3154008UL   ;
        mapDisplayOptions["__REG_SNAPFORMAT"                 ] = 3153948UL   ;
        mapDisplayOptions["__REG_SNAPSHOT"                   ] = 3153944UL   ;
        mapDisplayOptions["__REG_SNAPY"                      ] = 3153940UL   ;
        mapDisplayOptions["__REG_SOUND"                      ] = 3154056UL   ;
        mapDisplayOptions["__REG_SPI_EARLY_TX"               ] = 3154300UL   ;
        mapDisplayOptions["__REG_SPI_WIDTH"                  ] = 3154312UL   ;
        mapDisplayOptions["__REG_SWIZZLE"                    ] = 3154020UL   ;
        mapDisplayOptions["__REG_TAG"                        ] = 3154044UL   ;
        mapDisplayOptions["__REG_TAG_X"                      ] = 3154036UL   ;
        mapDisplayOptions["__REG_TAG_Y"                      ] = 3154040UL   ;
        mapDisplayOptions["__REG_TAP_CRC"                    ] = 3153956UL   ;
        mapDisplayOptions["__REG_TAP_MASK"                   ] = 3153960UL   ;
        mapDisplayOptions["__REG_TOUCH_ADC_MODE"             ] = 3154184UL   ;
        mapDisplayOptions["__REG_TOUCH_CHARGE"               ] = 3154188UL   ;
        mapDisplayOptions["__REG_TOUCH_DIRECT_XY"            ] = 3154316UL   ;
        mapDisplayOptions["__REG_TOUCH_DIRECT_Z1Z2"          ] = 3154320UL   ;
        mapDisplayOptions["__REG_TOUCH_FAULT"                ] = 3154288UL   ;
        mapDisplayOptions["__REG_TOUCH_MODE"                 ] = 3154180UL   ;
        mapDisplayOptions["__REG_TOUCH_OVERSAMPLE"           ] = 3154196UL   ;
        mapDisplayOptions["__REG_TOUCH_RAW_XY"               ] = 3154204UL   ;
        mapDisplayOptions["__REG_TOUCH_RZ"                   ] = 3154208UL   ;
        mapDisplayOptions["__REG_TOUCH_RZTHRESH"             ] = 3154200UL   ;
        mapDisplayOptions["__REG_TOUCH_SCREEN_XY"            ] = 3154212UL   ;
        mapDisplayOptions["__REG_TOUCH_SETTLE"               ] = 3154192UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG"                  ] = 3154220UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG1"                 ] = 3154228UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG1_XY"              ] = 3154224UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG2"                 ] = 3154236UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG2_XY"              ] = 3154232UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG3"                 ] = 3154244UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG3_XY"              ] = 3154240UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG4"                 ] = 3154252UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG4_XY"              ] = 3154248UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG_XY"               ] = 3154216UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_A"          ] = 3154256UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_B"          ] = 3154260UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_C"          ] = 3154264UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_D"          ] = 3154268UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_E"          ] = 3154272UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_F"          ] = 3154276UL   ;
        mapDisplayOptions["__REG_TRACKER"                    ] = 3182592UL   ;
        mapDisplayOptions["__REG_TRACKER_1"                  ] = 3182596UL   ;
        mapDisplayOptions["__REG_TRACKER_2"                  ] = 3182600UL   ;
        mapDisplayOptions["__REG_TRACKER_3"                  ] = 3182604UL   ;
        mapDisplayOptions["__REG_TRACKER_4"                  ] = 3182608UL   ;
        mapDisplayOptions["__REG_TRIM"                       ] = 3154304UL   ;
        mapDisplayOptions["__REG_VCYCLE"                     ] = 3153984UL   ;
        mapDisplayOptions["__REG_VOFFSET"                    ] = 3153988UL   ;
        mapDisplayOptions["__REG_VOL_PB"                     ] = 3154048UL   ;
        mapDisplayOptions["__REG_VOL_SOUND"                  ] = 3154052UL   ;
        mapDisplayOptions["__REG_VSIZE"                      ] = 3153992UL   ;
        mapDisplayOptions["__REG_VSYNC0"                     ] = 3153996UL   ;
        mapDisplayOptions["__REG_VSYNC1"                     ] = 3154000UL   ;
        mapDisplayOptions["__REPEAT"                         ] = 1UL         ;
        mapDisplayOptions["__REPLACE"                        ] = 2UL         ;
        mapDisplayOptions["__RGB332"                         ] = 4UL         ;
        mapDisplayOptions["__RGB565"                         ] = 7UL         ;
        mapDisplayOptions["__SRC_ALPHA"                      ] = 2UL         ;
        mapDisplayOptions["__TEXT8X8"                        ] = 9UL         ;
        mapDisplayOptions["__TEXTVGA"                        ] = 10UL        ;
        mapDisplayOptions["__TOUCHMODE_CONTINUOUS"           ] = 3UL         ;
        mapDisplayOptions["__TOUCHMODE_FRAME"                ] = 2UL         ;
        mapDisplayOptions["__TOUCHMODE_OFF"                  ] = 0UL         ;
        mapDisplayOptions["__TOUCHMODE_ONESHOT"              ] = 1UL         ;
        mapDisplayOptions["__ULAW_SAMPLES"                   ] = 1UL         ;
        mapDisplayOptions["__ZERO"                           ] = 0UL         ;
        break;
    case DisplaySettings::dgEve3:
        mapDisplayOptions["__LOW_FREQ_BOUND"                 ] = 58800000L   ;
        mapDisplayOptions["__RAM_G_SIZE"                     ] = 1024*1024L  ;
        mapDisplayOptions["__FLASH_DEFAULT_SHA1KEY"          ] = 0xf589cf07  ;
        mapDisplayOptions["__PPC"                            ] = 16          ;
        mapDisplayOptions["__BANKS"                          ] = 16          ;
        mapDisplayOptions["__BANKW"                          ] = 16          ;
        mapDisplayOptions["__ADC_DIFFERENTIAL"               ] = 1UL         ;
        mapDisplayOptions["__ADC_SINGLE_ENDED"               ] = 0UL         ;
        mapDisplayOptions["__ADPCM_SAMPLES"                  ] = 2UL         ;
        mapDisplayOptions["__ALPHA"                          ] = 5UL         ;
        mapDisplayOptions["__ALWAYS"                         ] = 7UL         ;
        mapDisplayOptions["__ANIM_HOLD"                      ] = 2UL         ;
        mapDisplayOptions["__ANIM_LOOP"                      ] = 1UL         ;
        mapDisplayOptions["__ANIM_ONCE"                      ] = 0UL         ;
        mapDisplayOptions["__ARGB1555"                       ] = 0UL         ;
        mapDisplayOptions["__ARGB2"                          ] = 5UL         ;
        mapDisplayOptions["__ARGB4"                          ] = 6UL         ;
        mapDisplayOptions["__BARGRAPH"                       ] = 11UL        ;
        mapDisplayOptions["__BILINEAR"                       ] = 1UL         ;
        mapDisplayOptions["__BITMAPS"                        ] = 1UL         ;
        mapDisplayOptions["__BLUE"                           ] = 4UL         ;
        mapDisplayOptions["__BORDER"                         ] = 0UL         ;
        mapDisplayOptions["__CMDBUF_SIZE"                    ] = 4096UL      ;
        mapDisplayOptions["__CMD_ANIMDRAW"                   ] = 4294967126UL;
        mapDisplayOptions["__CMD_ANIMFRAME"                  ] = 4294967130UL;
        mapDisplayOptions["__CMD_ANIMSTART"                  ] = 4294967123UL;
        mapDisplayOptions["__CMD_ANIMSTOP"                   ] = 4294967124UL;
        mapDisplayOptions["__CMD_ANIMXY"                     ] = 4294967125UL;
        mapDisplayOptions["__CMD_APPEND"                     ] = 4294967070UL;
        mapDisplayOptions["__CMD_APPENDF"                    ] = 4294967129UL;
        mapDisplayOptions["__CMD_BGCOLOR"                    ] = 4294967049UL;
        mapDisplayOptions["__CMD_BITMAP_TRANSFORM"           ] = 4294967073UL;
        mapDisplayOptions["__CMD_BUTTON"                     ] = 4294967053UL;
        mapDisplayOptions["__CMD_CALIBRATE"                  ] = 4294967061UL;
        mapDisplayOptions["__CMD_CLEARCACHE"                 ] = 4294967119UL;
        mapDisplayOptions["__CMD_CLOCK"                      ] = 4294967060UL;
        mapDisplayOptions["__CMD_COLDSTART"                  ] = 4294967090UL;
        mapDisplayOptions["__CMD_CRC"                        ] = 4294967043UL;
        mapDisplayOptions["__CMD_DEPRECATED_CSKETCH"         ] = 4294967093UL;
        mapDisplayOptions["__CMD_DIAL"                       ] = 4294967085UL;
        mapDisplayOptions["__CMD_DLSTART"                    ] = 4294967040UL;
        mapDisplayOptions["__CMD_EXECUTE"                    ] = 4294967047UL;
        mapDisplayOptions["__CMD_FGCOLOR"                    ] = 4294967050UL;
        mapDisplayOptions["__CMD_FILLWIDTH"                  ] = 4294967128UL;
        mapDisplayOptions["__CMD_FLASHATTACH"                ] = 4294967113UL;
        mapDisplayOptions["__CMD_FLASHDETACH"                ] = 4294967112UL;
        mapDisplayOptions["__CMD_FLASHERASE"                 ] = 4294967108UL;
        mapDisplayOptions["__CMD_FLASHFAST"                  ] = 4294967114UL;
        mapDisplayOptions["__CMD_FLASHREAD"                  ] = 4294967110UL;
        mapDisplayOptions["__CMD_FLASHSOURCE"                ] = 4294967118UL;
        mapDisplayOptions["__CMD_FLASHSPIDESEL"              ] = 4294967115UL;
        mapDisplayOptions["__CMD_FLASHSPIRX"                 ] = 4294967117UL;
        mapDisplayOptions["__CMD_FLASHSPITX"                 ] = 4294967116UL;
        mapDisplayOptions["__CMD_FLASHUPDATE"                ] = 4294967111UL;
        mapDisplayOptions["__CMD_FLASHWRITE"                 ] = 4294967109UL;
        mapDisplayOptions["__CMD_GAUGE"                      ] = 4294967059UL;
        mapDisplayOptions["__CMD_GETMATRIX"                  ] = 4294967091UL;
        mapDisplayOptions["__CMD_GETPOINT"                   ] = 4294967048UL;
        mapDisplayOptions["__CMD_GETPROPS"                   ] = 4294967077UL;
        mapDisplayOptions["__CMD_GETPTR"                     ] = 4294967075UL;
        mapDisplayOptions["__CMD_GRADCOLOR"                  ] = 4294967092UL;
        mapDisplayOptions["__CMD_GRADIENT"                   ] = 4294967051UL;
        mapDisplayOptions["__CMD_GRADIENTA"                  ] = 4294967127UL;
        mapDisplayOptions["__CMD_HAMMERAUX"                  ] = 4294967044UL;
        mapDisplayOptions["__CMD_HMAC"                       ] = 4294967133UL;
        mapDisplayOptions["__CMD_IDCT_DELETED"               ] = 4294967046UL;
        mapDisplayOptions["__CMD_INFLATE"                    ] = 4294967074UL;
        mapDisplayOptions["__CMD_INFLATE2"                   ] = 4294967120UL;
        mapDisplayOptions["__CMD_INTERRUPT"                  ] = 4294967042UL;
        mapDisplayOptions["__CMD_INT_RAMSHARED"              ] = 4294967101UL;
        mapDisplayOptions["__CMD_INT_SWLOADIMAGE"            ] = 4294967102UL;
        mapDisplayOptions["__CMD_KEYS"                       ] = 4294967054UL;
        mapDisplayOptions["__CMD_LAST_"                      ] = 4294967134UL;
        mapDisplayOptions["__CMD_LOADIDENTITY"               ] = 4294967078UL;
        mapDisplayOptions["__CMD_LOADIMAGE"                  ] = 4294967076UL;
        mapDisplayOptions["__CMD_LOGO"                       ] = 4294967089UL;
        mapDisplayOptions["__CMD_MARCH"                      ] = 4294967045UL;
        mapDisplayOptions["__CMD_MEDIAFIFO"                  ] = 4294967097UL;
        mapDisplayOptions["__CMD_MEMCPY"                     ] = 4294967069UL;
        mapDisplayOptions["__CMD_MEMCRC"                     ] = 4294967064UL;
        mapDisplayOptions["__CMD_MEMSET"                     ] = 4294967067UL;
        mapDisplayOptions["__CMD_MEMWRITE"                   ] = 4294967066UL;
        mapDisplayOptions["__CMD_MEMZERO"                    ] = 4294967068UL;
        mapDisplayOptions["__CMD_NOP"                        ] = 4294967131UL;
        mapDisplayOptions["__CMD_NUMBER"                     ] = 4294967086UL;
        mapDisplayOptions["__CMD_PLAYVIDEO"                  ] = 4294967098UL;
        mapDisplayOptions["__CMD_PROGRESS"                   ] = 4294967055UL;
        mapDisplayOptions["__CMD_REGREAD"                    ] = 4294967065UL;
        mapDisplayOptions["__CMD_RESETFONTS"                 ] = 4294967122UL;
        mapDisplayOptions["__CMD_ROMFONT"                    ] = 4294967103UL;
        mapDisplayOptions["__CMD_ROTATE"                     ] = 4294967081UL;
        mapDisplayOptions["__CMD_ROTATEAROUND"               ] = 4294967121UL;
        mapDisplayOptions["__CMD_SCALE"                      ] = 4294967080UL;
        mapDisplayOptions["__CMD_SCREENSAVER"                ] = 4294967087UL;
        mapDisplayOptions["__CMD_SCROLLBAR"                  ] = 4294967057UL;
        mapDisplayOptions["__CMD_SETBASE"                    ] = 4294967096UL;
        mapDisplayOptions["__CMD_SETBITMAP"                  ] = 4294967107UL;
        mapDisplayOptions["__CMD_SETFONT"                    ] = 4294967083UL;
        mapDisplayOptions["__CMD_SETFONT2"                   ] = 4294967099UL;
        mapDisplayOptions["__CMD_SETMATRIX"                  ] = 4294967082UL;
        mapDisplayOptions["__CMD_SETROTATE"                  ] = 4294967094UL;
        mapDisplayOptions["__CMD_SETSCRATCH"                 ] = 4294967100UL;
        mapDisplayOptions["__CMD_SHA1"                       ] = 4294967132UL;
        mapDisplayOptions["__CMD_SKETCH"                     ] = 4294967088UL;
        mapDisplayOptions["__CMD_SLIDER"                     ] = 4294967056UL;
        mapDisplayOptions["__CMD_SNAPSHOT"                   ] = 4294967071UL;
        mapDisplayOptions["__CMD_SNAPSHOT2"                  ] = 4294967095UL;
        mapDisplayOptions["__CMD_SPINNER"                    ] = 4294967062UL;
        mapDisplayOptions["__CMD_STOP"                       ] = 4294967063UL;
        mapDisplayOptions["__CMD_SWAP"                       ] = 4294967041UL;
        mapDisplayOptions["__CMD_SYNC"                       ] = 4294967106UL;
        mapDisplayOptions["__CMD_TEXT"                       ] = 4294967052UL;
        mapDisplayOptions["__CMD_TOGGLE"                     ] = 4294967058UL;
        mapDisplayOptions["__CMD_TOUCH_TRANSFORM"            ] = 4294967072UL;
        mapDisplayOptions["__CMD_TRACK"                      ] = 4294967084UL;
        mapDisplayOptions["__CMD_TRANSLATE"                  ] = 4294967079UL;
        mapDisplayOptions["__CMD_VIDEOFRAME"                 ] = 4294967105UL;
        mapDisplayOptions["__CMD_VIDEOSTART"                 ] = 4294967104UL;
        mapDisplayOptions["__CMD_VIDEOSTARTF"                ] = 4294967135UL;
        mapDisplayOptions["__COMPRESSED_RGBA_ASTC_10x10_KHR" ] = 37819UL     ;
        mapDisplayOptions["__COMPRESSED_RGBA_ASTC_10x5_KHR"  ] = 37816UL     ;
        mapDisplayOptions["__COMPRESSED_RGBA_ASTC_10x6_KHR"  ] = 37817UL     ;
        mapDisplayOptions["__COMPRESSED_RGBA_ASTC_10x8_KHR"  ] = 37818UL     ;
        mapDisplayOptions["__COMPRESSED_RGBA_ASTC_12x10_KHR" ] = 37820UL     ;
        mapDisplayOptions["__COMPRESSED_RGBA_ASTC_12x12_KHR" ] = 37821UL     ;
        mapDisplayOptions["__COMPRESSED_RGBA_ASTC_4x4_KHR"   ] = 37808UL     ;
        mapDisplayOptions["__COMPRESSED_RGBA_ASTC_5x4_KHR"   ] = 37809UL     ;
        mapDisplayOptions["__COMPRESSED_RGBA_ASTC_5x5_KHR"   ] = 37810UL     ;
        mapDisplayOptions["__COMPRESSED_RGBA_ASTC_6x5_KHR"   ] = 37811UL     ;
        mapDisplayOptions["__COMPRESSED_RGBA_ASTC_6x6_KHR"   ] = 37812UL     ;
        mapDisplayOptions["__COMPRESSED_RGBA_ASTC_8x5_KHR"   ] = 37813UL     ;
        mapDisplayOptions["__COMPRESSED_RGBA_ASTC_8x6_KHR"   ] = 37814UL     ;
        mapDisplayOptions["__COMPRESSED_RGBA_ASTC_8x8_KHR"   ] = 37815UL     ;
        mapDisplayOptions["__CTOUCH_MODE_COMPATIBILITY"      ] = 1UL         ;
        mapDisplayOptions["__CTOUCH_MODE_EXTENDED"           ] = 0UL         ;
        mapDisplayOptions["__DECR"                           ] = 4UL         ;
        mapDisplayOptions["__DLSWAP_DONE"                    ] = 0UL         ;
        mapDisplayOptions["__DLSWAP_FRAME"                   ] = 2UL         ;
        mapDisplayOptions["__DLSWAP_LINE"                    ] = 1UL         ;
        mapDisplayOptions["__DST_ALPHA"                      ] = 3UL         ;
        mapDisplayOptions["__EDGE_STRIP_A"                   ] = 7UL         ;
        mapDisplayOptions["__EDGE_STRIP_B"                   ] = 8UL         ;
        mapDisplayOptions["__EDGE_STRIP_L"                   ] = 6UL         ;
        mapDisplayOptions["__EDGE_STRIP_R"                   ] = 5UL         ;
        mapDisplayOptions["__EQUAL"                          ] = 5UL         ;
        mapDisplayOptions["__FLASH_STATUS_BASIC"             ] = 2UL         ;
        mapDisplayOptions["__FLASH_STATUS_DETACHED"          ] = 1UL         ;
        mapDisplayOptions["__FLASH_STATUS_FULL"              ] = 3UL         ;
        mapDisplayOptions["__FLASH_STATUS_INIT"              ] = 0UL         ;
        mapDisplayOptions["__GEQUAL"                         ] = 4UL         ;
        mapDisplayOptions["__GLFORMAT"                       ] = 31UL        ;
        mapDisplayOptions["__GREATER"                        ] = 3UL         ;
        mapDisplayOptions["__GREEN"                          ] = 3UL         ;
        mapDisplayOptions["__INCR"                           ] = 3UL         ;
        mapDisplayOptions["__INT_CMDEMPTY"                   ] = 32UL        ;
        mapDisplayOptions["__INT_CMDFLAG"                    ] = 64UL        ;
        mapDisplayOptions["__INT_CONVCOMPLETE"               ] = 128UL       ;
        mapDisplayOptions["__INT_G8"                         ] = 18UL        ;
        mapDisplayOptions["__INT_L8C"                        ] = 12UL        ;
        mapDisplayOptions["__INT_PLAYBACK"                   ] = 16UL        ;
        mapDisplayOptions["__INT_SOUND"                      ] = 8UL         ;
        mapDisplayOptions["__INT_SWAP"                       ] = 1UL         ;
        mapDisplayOptions["__INT_TAG"                        ] = 4UL         ;
        mapDisplayOptions["__INT_TOUCH"                      ] = 2UL         ;
        mapDisplayOptions["__INT_VGA"                        ] = 13UL        ;
        mapDisplayOptions["__INVERT"                         ] = 5UL         ;
        mapDisplayOptions["__JT_CYA"                         ] = 9UL         ;
        mapDisplayOptions["__JT_DRIVES"                      ] = 4UL         ;
        mapDisplayOptions["__JT_FRAMES"                      ] = 6UL         ;
        mapDisplayOptions["__JT_ONESHOT"                     ] = 7UL         ;
        mapDisplayOptions["__JT_PEN"                         ] = 5UL         ;
        mapDisplayOptions["__JT_PWM"                         ] = 8UL         ;
        mapDisplayOptions["__JT_RI_ADC_MODE"                 ] = 14UL        ;
        mapDisplayOptions["__JT_RI_CHARGE"                   ] = 13UL        ;
        mapDisplayOptions["__JT_RI_CTOUCH_EXTENDED"          ] = 14UL        ;
        mapDisplayOptions["__JT_RI_EHOST_ID"                 ] = 16UL        ;
        mapDisplayOptions["__JT_RI_EHOST_X"                  ] = 13UL        ;
        mapDisplayOptions["__JT_RI_EHOST_Y"                  ] = 17UL        ;
        mapDisplayOptions["__JT_RI_INT"                      ] = 45UL        ;
        mapDisplayOptions["__JT_RI_MODE"                     ] = 12UL        ;
        mapDisplayOptions["__JT_RI_OVERSAMPLE"               ] = 16UL        ;
        mapDisplayOptions["__JT_RI_RZTHRESH"                 ] = 17UL        ;
        mapDisplayOptions["__JT_RI_SETTLE"                   ] = 15UL        ;
        mapDisplayOptions["__JT_RI_SHORTS"                   ] = 31UL        ;
        mapDisplayOptions["__JT_RI_UART_BUSY"                ] = 30UL        ;
        mapDisplayOptions["__JT_RI_XF_AH"                    ] = 19UL        ;
        mapDisplayOptions["__JT_RI_XF_AL"                    ] = 18UL        ;
        mapDisplayOptions["__JT_RI_XF_BH"                    ] = 21UL        ;
        mapDisplayOptions["__JT_RI_XF_BL"                    ] = 20UL        ;
        mapDisplayOptions["__JT_RI_XF_CH"                    ] = 23UL        ;
        mapDisplayOptions["__JT_RI_XF_CL"                    ] = 22UL        ;
        mapDisplayOptions["__JT_RI_XF_DH"                    ] = 25UL        ;
        mapDisplayOptions["__JT_RI_XF_DL"                    ] = 24UL        ;
        mapDisplayOptions["__JT_RI_XF_EH"                    ] = 27UL        ;
        mapDisplayOptions["__JT_RI_XF_EL"                    ] = 26UL        ;
        mapDisplayOptions["__JT_RI_XF_FH"                    ] = 29UL        ;
        mapDisplayOptions["__JT_RI_XF_FL"                    ] = 28UL        ;
        mapDisplayOptions["__JT_RO_ANALOG"                   ] = 37UL        ;
        mapDisplayOptions["__JT_RO_CTOUCH_TOUCH0_XY"         ] = 34UL        ;
        mapDisplayOptions["__JT_RO_CTOUCH_TOUCH4X"           ] = 37UL        ;
        mapDisplayOptions["__JT_RO_CTOUCH_TOUCH4Y"           ] = 33UL        ;
        mapDisplayOptions["__JT_RO_CTOUCH_TOUCHA_XY"         ] = 32UL        ;
        mapDisplayOptions["__JT_RO_CTOUCH_TOUCHB_XY"         ] = 35UL        ;
        mapDisplayOptions["__JT_RO_CTOUCH_TOUCHC_XY"         ] = 36UL        ;
        mapDisplayOptions["__JT_RO_DIRECT_XY"                ] = 35UL        ;
        mapDisplayOptions["__JT_RO_DIRECT_Z1Z2"              ] = 36UL        ;
        mapDisplayOptions["__JT_RO_EHOST_ACK"                ] = 41UL        ;
        mapDisplayOptions["__JT_RO_FAULT"                    ] = 41UL        ;
        mapDisplayOptions["__JT_RO_INTERRUPT"                ] = 39UL        ;
        mapDisplayOptions["__JT_RO_RAW_XY"                   ] = 32UL        ;
        mapDisplayOptions["__JT_RO_RZ"                       ] = 33UL        ;
        mapDisplayOptions["__JT_RO_SCREEN_XY"                ] = 34UL        ;
        mapDisplayOptions["__JT_RO_SHORT_DETECT"             ] = 40UL        ;
        mapDisplayOptions["__JT_RO_UART"                     ] = 38UL        ;
        mapDisplayOptions["__JT_RO_WAKE"                     ] = 44UL        ;
        mapDisplayOptions["__JT_R_SCRATCH"                   ] = 11UL        ;
        mapDisplayOptions["__JT_SCL"                         ] = 42UL        ;
        mapDisplayOptions["__JT_SDA"                         ] = 43UL        ;
        mapDisplayOptions["__JT_TICK"                        ] = 10UL        ;
        mapDisplayOptions["__JT_XD"                          ] = 3UL         ;
        mapDisplayOptions["__JT_XEOC"                        ] = 2UL         ;
        mapDisplayOptions["__JT_XMCLK"                       ] = 0UL         ;
        mapDisplayOptions["__JT_XSAMP_CLK"                   ] = 1UL         ;
        mapDisplayOptions["__KEEP"                           ] = 1UL         ;
        mapDisplayOptions["__L1"                             ] = 1UL         ;
        mapDisplayOptions["__L2"                             ] = 17UL        ;
        mapDisplayOptions["__L4"                             ] = 2UL         ;
        mapDisplayOptions["__L8"                             ] = 3UL         ;
        mapDisplayOptions["__LEQUAL"                         ] = 2UL         ;
        mapDisplayOptions["__LESS"                           ] = 1UL         ;
        mapDisplayOptions["__LINEAR_SAMPLES"                 ] = 0UL         ;
        mapDisplayOptions["__LINES"                          ] = 3UL         ;
        mapDisplayOptions["__LINE_STRIP"                     ] = 4UL         ;
        mapDisplayOptions["__NEAREST"                        ] = 0UL         ;
        mapDisplayOptions["__NEVER"                          ] = 0UL         ;
        mapDisplayOptions["__NOTEQUAL"                       ] = 6UL         ;
        mapDisplayOptions["__ONE"                            ] = 1UL         ;
        mapDisplayOptions["__ONE_MINUS_DST_ALPHA"            ] = 5UL         ;
        mapDisplayOptions["__ONE_MINUS_SRC_ALPHA"            ] = 4UL         ;
        mapDisplayOptions["__OPT_CENTER"                     ] = 1536UL      ;
        mapDisplayOptions["__OPT_CENTERX"                    ] = 512UL       ;
        mapDisplayOptions["__OPT_CENTERY"                    ] = 1024UL      ;
        mapDisplayOptions["__OPT_FILL"                       ] = 8192UL      ;
        mapDisplayOptions["__OPT_FLASH"                      ] = 64UL        ;
        mapDisplayOptions["__OPT_FLAT"                       ] = 256UL       ;
        mapDisplayOptions["__OPT_FORMAT"                     ] = 4096UL      ;
        mapDisplayOptions["__OPT_FULLSCREEN"                 ] = 8UL         ;
        mapDisplayOptions["__OPT_MEDIAFIFO"                  ] = 16UL        ;
        mapDisplayOptions["__OPT_MONO"                       ] = 1UL         ;
        mapDisplayOptions["__OPT_NOBACK"                     ] = 4096UL      ;
        mapDisplayOptions["__OPT_NODL"                       ] = 2UL         ;
        mapDisplayOptions["__OPT_NOHANDS"                    ] = 49152UL     ;
        mapDisplayOptions["__OPT_NOHM"                       ] = 16384UL     ;
        mapDisplayOptions["__OPT_NOPOINTER"                  ] = 16384UL     ;
        mapDisplayOptions["__OPT_NOSECS"                     ] = 32768UL     ;
        mapDisplayOptions["__OPT_NOTEAR"                     ] = 4UL         ;
        mapDisplayOptions["__OPT_NOTICKS"                    ] = 8192UL      ;
        mapDisplayOptions["__OPT_OVERLAY"                    ] = 128UL       ;
        mapDisplayOptions["__OPT_RIGHTX"                     ] = 2048UL      ;
        mapDisplayOptions["__OPT_SIGNED"                     ] = 256UL       ;
        mapDisplayOptions["__OPT_SOUND"                      ] = 32UL        ;
        mapDisplayOptions["__PALETTED"                       ] = 8UL         ;
        mapDisplayOptions["__PALETTED4444"                   ] = 15UL        ;
        mapDisplayOptions["__PALETTED565"                    ] = 14UL        ;
        mapDisplayOptions["__PALETTED8"                      ] = 16UL        ;
        mapDisplayOptions["__FTPOINTS"                       ] = 2UL         ;
        mapDisplayOptions["__RAM_BIST"                       ] = 3670016UL   ;
        mapDisplayOptions["__RAM_CMD"                        ] = 3178496UL   ;
        mapDisplayOptions["__RAM_DL"                         ] = 3145728UL   ;
        mapDisplayOptions["__RAM_G"                          ] = 0UL         ;
        mapDisplayOptions["__RAM_J1RAM"                      ] = 3182592UL   ;
        mapDisplayOptions["__RAM_JTBOOT"                     ] = 3190784UL   ;
        mapDisplayOptions["__RAM_REG"                        ] = 3153920UL   ;
        mapDisplayOptions["__RAM_ROMSUB"                     ] = 3186688UL   ;
        mapDisplayOptions["__RAM_TOP"                        ] = 3162112UL   ;
        mapDisplayOptions["__RECTS"                          ] = 9UL         ;
        mapDisplayOptions["__RED"                            ] = 2UL         ;
        mapDisplayOptions["__REG_ADAPTIVE_FRAMERATE"         ] = 3155324UL   ;
        mapDisplayOptions["__REG_ANALOG"                     ] = 3154284UL   ;
        mapDisplayOptions["__REG_ANA_COMP"                   ] = 3154308UL   ;
        mapDisplayOptions["__REG_ANIM_ACTIVE"                ] = 3182636UL   ;
        mapDisplayOptions["__REG_BIST_EN"                    ] = 3154292UL   ;
        mapDisplayOptions["__REG_BUSYBITS"                   ] = 3154152UL   ;
        mapDisplayOptions["__REG_CLOCK"                      ] = 3153928UL   ;
        mapDisplayOptions["__REG_CMDB_SPACE"                 ] = 3155316UL   ;
        mapDisplayOptions["__REG_CMDB_WRITE"                 ] = 3155320UL   ;
        mapDisplayOptions["__REG_CMD_DL"                     ] = 3154176UL   ;
        mapDisplayOptions["__REG_CMD_READ"                   ] = 3154168UL   ;
        mapDisplayOptions["__REG_CMD_WRITE"                  ] = 3154172UL   ;
        mapDisplayOptions["__REG_CPURESET"                   ] = 3153952UL   ;
        mapDisplayOptions["__REG_CRC"                        ] = 3154296UL   ;
        mapDisplayOptions["__REG_CSPREAD"                    ] = 3154024UL   ;
        mapDisplayOptions["__REG_CTOUCH_EXTENDED"            ] = 3154184UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH0_XY"           ] = 3154212UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH4_X"            ] = 3154284UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH4_Y"            ] = 3154208UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCHA_XY"           ] = 3154204UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCHB_XY"           ] = 3154316UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCHC_XY"           ] = 3154320UL   ;
        mapDisplayOptions["__REG_CYA0"                       ] = 3154144UL   ;
        mapDisplayOptions["__REG_CYA1"                       ] = 3154148UL   ;
        mapDisplayOptions["__REG_CYA_TOUCH"                  ] = 3154280UL   ;
        mapDisplayOptions["__REG_DATESTAMP"                  ] = 3155300UL   ;
        mapDisplayOptions["__REG_DF_TUNED"                   ] = 3182640UL   ;
        mapDisplayOptions["__REG_DITHER"                     ] = 3154016UL   ;
        mapDisplayOptions["__REG_DLSWAP"                     ] = 3154004UL   ;
        mapDisplayOptions["__REG_EHOST_TOUCH_ACK"            ] = 3154288UL   ;
        mapDisplayOptions["__REG_EHOST_TOUCH_ID"             ] = 3154196UL   ;
        mapDisplayOptions["__REG_EHOST_TOUCH_X"              ] = 3154188UL   ;
        mapDisplayOptions["__REG_EHOST_TOUCH_Y"              ] = 3154200UL   ;
        mapDisplayOptions["__REG_EJPG_ACC"                   ] = 3154776UL   ;
        mapDisplayOptions["__REG_EJPG_BUSY"                  ] = 3154328UL   ;
        mapDisplayOptions["__REG_EJPG_DAT"                   ] = 3154332UL   ;
        mapDisplayOptions["__REG_EJPG_DCC"                   ] = 3154752UL   ;
        mapDisplayOptions["__REG_EJPG_DEBUG"                 ] = 3155292UL   ;
        mapDisplayOptions["__REG_EJPG_DST"                   ] = 3154340UL   ;
        mapDisplayOptions["__REG_EJPG_FORMAT"                ] = 3154352UL   ;
        mapDisplayOptions["__REG_EJPG_H"                     ] = 3154348UL   ;
        mapDisplayOptions["__REG_EJPG_HT"                    ] = 3154496UL   ;
        mapDisplayOptions["__REG_EJPG_OPTIONS"               ] = 3154336UL   ;
        mapDisplayOptions["__REG_EJPG_Q"                     ] = 3154368UL   ;
        mapDisplayOptions["__REG_EJPG_READY"                 ] = 3154324UL   ;
        mapDisplayOptions["__REG_EJPG_RI"                    ] = 3154356UL   ;
        mapDisplayOptions["__REG_EJPG_SCALE"                 ] = 3155288UL   ;
        mapDisplayOptions["__REG_EJPG_TDA"                   ] = 3154364UL   ;
        mapDisplayOptions["__REG_EJPG_TQ"                    ] = 3154360UL   ;
        mapDisplayOptions["__REG_EJPG_W"                     ] = 3154344UL   ;
        mapDisplayOptions["__REG_ESPIM_ADD"                  ] = 3155356UL   ;
        mapDisplayOptions["__REG_ESPIM_COUNT"                ] = 3155360UL   ;
        mapDisplayOptions["__REG_ESPIM_DUMMY"                ] = 3155428UL   ;
        mapDisplayOptions["__REG_ESPIM_READSTART"            ] = 3155336UL   ;
        mapDisplayOptions["__REG_ESPIM_SEQ"                  ] = 3155340UL   ;
        mapDisplayOptions["__REG_ESPIM_TRIG"                 ] = 3155432UL   ;
        mapDisplayOptions["__REG_ESPIM_WINDOW"               ] = 3155364UL   ;
        mapDisplayOptions["__REG_FLASH_SIZE"                 ] = 3182628UL   ;
        mapDisplayOptions["__REG_FLASH_STATUS"               ] = 3155440UL   ;
        mapDisplayOptions["__REG_FRAMES"                     ] = 3153924UL   ;
        mapDisplayOptions["__REG_FREQUENCY"                  ] = 3153932UL   ;
        mapDisplayOptions["__REG_FULLBUSYBITS"               ] = 3155444UL   ;
        mapDisplayOptions["__REG_GPIO"                       ] = 3154068UL   ;
        mapDisplayOptions["__REG_GPIOX"                      ] = 3154076UL   ;
        mapDisplayOptions["__REG_GPIOX_DIR"                  ] = 3154072UL   ;
        mapDisplayOptions["__REG_GPIO_DIR"                   ] = 3154064UL   ;
        mapDisplayOptions["__REG_HCYCLE"                     ] = 3153964UL   ;
        mapDisplayOptions["__REG_HOFFSET"                    ] = 3153968UL   ;
        mapDisplayOptions["__REG_HSIZE"                      ] = 3153972UL   ;
        mapDisplayOptions["__REG_HSYNC0"                     ] = 3153976UL   ;
        mapDisplayOptions["__REG_HSYNC1"                     ] = 3153980UL   ;
        mapDisplayOptions["__REG_ID"                         ] = 3153920UL   ;
        mapDisplayOptions["__REG_INT_EN"                     ] = 3154092UL   ;
        mapDisplayOptions["__REG_INT_FLAGS"                  ] = 3154088UL   ;
        mapDisplayOptions["__REG_INT_MASK"                   ] = 3154096UL   ;
        mapDisplayOptions["__REG_J1_COLD"                    ] = 3154080UL   ;
        mapDisplayOptions["__REG_J1_INT"                     ] = 3154084UL   ;
        mapDisplayOptions["__REG_MACRO_0"                    ] = 3154136UL   ;
        mapDisplayOptions["__REG_MACRO_1"                    ] = 3154140UL   ;
        mapDisplayOptions["__REG_MEDIAFIFO_BASE"             ] = 3182620UL   ;
        mapDisplayOptions["__REG_MEDIAFIFO_READ"             ] = 3182612UL   ;
        mapDisplayOptions["__REG_MEDIAFIFO_SIZE"             ] = 3182624UL   ;
        mapDisplayOptions["__REG_MEDIAFIFO_WRITE"            ] = 3182616UL   ;
        mapDisplayOptions["__REG_OUTBITS"                    ] = 3154012UL   ;
        mapDisplayOptions["__REG_PATCHED_ANALOG"             ] = 3154288UL   ;
        mapDisplayOptions["__REG_PATCHED_TOUCH_FAULT"        ] = 3154284UL   ;
        mapDisplayOptions["__REG_PCLK"                       ] = 3154032UL   ;
        mapDisplayOptions["__REG_PCLK_POL"                   ] = 3154028UL   ;
        mapDisplayOptions["__REG_PLAY"                       ] = 3154060UL   ;
        mapDisplayOptions["__REG_PLAYBACK_FORMAT"            ] = 3154116UL   ;
        mapDisplayOptions["__REG_PLAYBACK_FREQ"              ] = 3154112UL   ;
        mapDisplayOptions["__REG_PLAYBACK_LENGTH"            ] = 3154104UL   ;
        mapDisplayOptions["__REG_PLAYBACK_LOOP"              ] = 3154120UL   ;
        mapDisplayOptions["__REG_PLAYBACK_PAUSE"             ] = 3155436UL   ;
        mapDisplayOptions["__REG_PLAYBACK_PLAY"              ] = 3154124UL   ;
        mapDisplayOptions["__REG_PLAYBACK_READPTR"           ] = 3154108UL   ;
        mapDisplayOptions["__REG_PLAYBACK_START"             ] = 3154100UL   ;
        mapDisplayOptions["__REG_PLAY_CONTROL"               ] = 3182926UL   ;
        mapDisplayOptions["__REG_PWM_DUTY"                   ] = 3154132UL   ;
        mapDisplayOptions["__REG_PWM_HZ"                     ] = 3154128UL   ;
        mapDisplayOptions["__REG_RAM_FOLD"                   ] = 3154164UL   ;
        mapDisplayOptions["__REG_RASTERY"                    ] = 3155296UL   ;
        mapDisplayOptions["__REG_RENDERMODE"                 ] = 3153936UL   ;
        mapDisplayOptions["__REG_ROMSUB_SEL"                 ] = 3154160UL   ;
        mapDisplayOptions["__REG_ROTATE"                     ] = 3154008UL   ;
        mapDisplayOptions["__REG_SHA1KEY"                    ] = 3155460UL   ;
        mapDisplayOptions["__REG_SNAPFORMAT"                 ] = 3153948UL   ;
        mapDisplayOptions["__REG_SNAPSHOT"                   ] = 3153944UL   ;
        mapDisplayOptions["__REG_SNAPY"                      ] = 3153940UL   ;
        mapDisplayOptions["__REG_SOUND"                      ] = 3154056UL   ;
        mapDisplayOptions["__REG_SPIM"                       ] = 3155332UL   ;
        mapDisplayOptions["__REG_SPIM_DIR"                   ] = 3155328UL   ;
        mapDisplayOptions["__REG_SPI_EARLY_TX"               ] = 3154300UL   ;
        mapDisplayOptions["__REG_SPI_WIDTH"                  ] = 3154312UL   ;
        mapDisplayOptions["__REG_SWIZZLE"                    ] = 3154020UL   ;
        mapDisplayOptions["__REG_TAG"                        ] = 3154044UL   ;
        mapDisplayOptions["__REG_TAG_X"                      ] = 3154036UL   ;
        mapDisplayOptions["__REG_TAG_Y"                      ] = 3154040UL   ;
        mapDisplayOptions["__REG_TAP_CRC"                    ] = 3153956UL   ;
        mapDisplayOptions["__REG_TAP_MASK"                   ] = 3153960UL   ;
        mapDisplayOptions["__REG_TOUCH_ADC_MODE"             ] = 3154184UL   ;
        mapDisplayOptions["__REG_TOUCH_CHARGE"               ] = 3154188UL   ;
        mapDisplayOptions["__REG_TOUCH_DIRECT_XY"            ] = 3154316UL   ;
        mapDisplayOptions["__REG_TOUCH_DIRECT_Z1Z2"          ] = 3154320UL   ;
        mapDisplayOptions["__REG_TOUCH_FAULT"                ] = 3154288UL   ;
        mapDisplayOptions["__REG_TOUCH_MODE"                 ] = 3154180UL   ;
        mapDisplayOptions["__REG_TOUCH_OVERSAMPLE"           ] = 3154196UL   ;
        mapDisplayOptions["__REG_TOUCH_RAW_XY"               ] = 3154204UL   ;
        mapDisplayOptions["__REG_TOUCH_RZ"                   ] = 3154208UL   ;
        mapDisplayOptions["__REG_TOUCH_RZTHRESH"             ] = 3154200UL   ;
        mapDisplayOptions["__REG_TOUCH_SCREEN_XY"            ] = 3154212UL   ;
        mapDisplayOptions["__REG_TOUCH_SETTLE"               ] = 3154192UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG"                  ] = 3154220UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG1"                 ] = 3154228UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG1_XY"              ] = 3154224UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG2"                 ] = 3154236UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG2_XY"              ] = 3154232UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG3"                 ] = 3154244UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG3_XY"              ] = 3154240UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG4"                 ] = 3154252UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG4_XY"              ] = 3154248UL   ;
        mapDisplayOptions["__REG_TOUCH_TAG_XY"               ] = 3154216UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_A"          ] = 3154256UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_B"          ] = 3154260UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_C"          ] = 3154264UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_D"          ] = 3154268UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_E"          ] = 3154272UL   ;
        mapDisplayOptions["__REG_TOUCH_TRANSFORM_F"          ] = 3154276UL   ;
        mapDisplayOptions["__REG_TRACKER"                    ] = 3182592UL   ;
        mapDisplayOptions["__REG_TRACKER_1"                  ] = 3182596UL   ;
        mapDisplayOptions["__REG_TRACKER_2"                  ] = 3182600UL   ;
        mapDisplayOptions["__REG_TRACKER_3"                  ] = 3182604UL   ;
        mapDisplayOptions["__REG_TRACKER_4"                  ] = 3182608UL   ;
        mapDisplayOptions["__REG_TRIM"                       ] = 3154304UL   ;
        mapDisplayOptions["__REG_VCYCLE"                     ] = 3153984UL   ;
        mapDisplayOptions["__REG_VOFFSET"                    ] = 3153988UL   ;
        mapDisplayOptions["__REG_VOL_PB"                     ] = 3154048UL   ;
        mapDisplayOptions["__REG_VOL_SOUND"                  ] = 3154052UL   ;
        mapDisplayOptions["__REG_VSIZE"                      ] = 3153992UL   ;
        mapDisplayOptions["__REG_VSYNC0"                     ] = 3153996UL   ;
        mapDisplayOptions["__REG_VSYNC1"                     ] = 3154000UL   ;
        mapDisplayOptions["__REPEAT"                         ] = 1UL         ;
        mapDisplayOptions["__REPLACE"                        ] = 2UL         ;
        mapDisplayOptions["__RGB332"                         ] = 4UL         ;
        mapDisplayOptions["__RGB565"                         ] = 7UL         ;
        mapDisplayOptions["__SRC_ALPHA"                      ] = 2UL         ;
        mapDisplayOptions["__SS_A0"                          ] = 19UL        ;
        mapDisplayOptions["__SS_A1"                          ] = 20UL        ;
        mapDisplayOptions["__SS_A2"                          ] = 21UL        ;
        mapDisplayOptions["__SS_A3"                          ] = 22UL        ;
        mapDisplayOptions["__SS_A4"                          ] = 23UL        ;
        mapDisplayOptions["__SS_A5"                          ] = 24UL        ;
        mapDisplayOptions["__SS_A6"                          ] = 25UL        ;
        mapDisplayOptions["__SS_A7"                          ] = 26UL        ;
        mapDisplayOptions["__SS_PAUSE"                       ] = 18UL        ;
        mapDisplayOptions["__SS_Q0"                          ] = 0UL         ;
        mapDisplayOptions["__SS_Q1"                          ] = 1UL         ;
        mapDisplayOptions["__SS_Q2"                          ] = 2UL         ;
        mapDisplayOptions["__SS_Q3"                          ] = 3UL         ;
        mapDisplayOptions["__SS_Q4"                          ] = 4UL         ;
        mapDisplayOptions["__SS_Q5"                          ] = 5UL         ;
        mapDisplayOptions["__SS_Q6"                          ] = 6UL         ;
        mapDisplayOptions["__SS_Q7"                          ] = 7UL         ;
        mapDisplayOptions["__SS_Q8"                          ] = 8UL         ;
        mapDisplayOptions["__SS_Q9"                          ] = 9UL         ;
        mapDisplayOptions["__SS_QA"                          ] = 10UL        ;
        mapDisplayOptions["__SS_QB"                          ] = 11UL        ;
        mapDisplayOptions["__SS_QC"                          ] = 12UL        ;
        mapDisplayOptions["__SS_QD"                          ] = 13UL        ;
        mapDisplayOptions["__SS_QE"                          ] = 14UL        ;
        mapDisplayOptions["__SS_QF"                          ] = 15UL        ;
        mapDisplayOptions["__SS_QI"                          ] = 31UL        ;
        mapDisplayOptions["__SS_S0"                          ] = 16UL        ;
        mapDisplayOptions["__SS_S1"                          ] = 17UL        ;
        mapDisplayOptions["__TEXT8X8"                        ] = 9UL         ;
        mapDisplayOptions["__TEXTVGA"                        ] = 10UL        ;
        mapDisplayOptions["__TOUCHMODE_CONTINUOUS"           ] = 3UL         ;
        mapDisplayOptions["__TOUCHMODE_FRAME"                ] = 2UL         ;
        mapDisplayOptions["__TOUCHMODE_OFF"                  ] = 0UL         ;
        mapDisplayOptions["__TOUCHMODE_ONESHOT"              ] = 1UL         ;
        mapDisplayOptions["__ULAW_SAMPLES"                   ] = 1UL         ;
        mapDisplayOptions["__ZERO"                           ] = 0UL         ;
        
        mapDisplayOptions["__RAM_ERR_REPORT"                 ] = 0x309800    ;
        mapDisplayOptions["__ROMFONT_TABLEADDRESS"           ] = 3145724UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH1_XY"           ] = 3154204UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH2_XY"           ] = 3154316UL   ;
        mapDisplayOptions["__REG_CTOUCH_TOUCH3_XY"           ] = 3154320UL   ;
        break;
    }
}

bool DisplaySettings::autoDetectDisplayGeneration()
{
    Gpu_Hal_Context_t tmp_host;

    Gpu_Hal_Init();
    Gpu_Hal_Open(&tmp_host);
    Gpu_Hal_Powercycle(true);

    /* FT81x will be in SPI Single channel after POR
    If we are here with FT4222 in multi channel, then
    an explicit switch to single channel is essential
    */
    if (!EVE1)
        Gpu_Hal_SetSPI(&tmp_host, GPU_SPI_SINGLE_CHANNEL, GPU_SPI_ONEDUMMY);

    /* access address 0 to wake up the chip */

#if (defined(EVE_2) && (defined(NTP_50)||defined(RTP_50)||defined(CTP_50)||defined(NTP_70)||defined(RTP_70)||defined(CTP_70)))
    Gpu_HostCommand(phost,GPU_INTERNAL_OSC);
#else
    Gpu_HostCommand(GPU_EXTERNAL_OSC);
#endif

    Gpu_HostCommand(GPU_PLL_48M);
    Gpu_HostCommand(GPU_ACTIVE_M);
    Gpu_Hal_Sleep(100);

    int trycount = 10;
    while (trycount --){
        unsigned int tmp = Gpu_Hal_Rd32(&tmp_host, FT_ROM_CHIPID);
        qDebug()<<tmp;
        if (tmp == 0x11508){
            setDisplayGeneration(dgEve3);
            return true;
        }
        else if (tmp == 0x10108) {
            setDisplayGeneration(dgEve1);
            return true;
        }
    }
    return false;
}

uint32_t DisplaySettings::operator[](const QString property)
{
    if (mapDisplaySizeSettings.contains(property))
        return mapDisplaySizeSettings[property];
    if (mapDisplayOptions.contains(property))
        return mapDisplayOptions[property];
    qCritical()<<"Property:"<<property<<"Not founded";
    assert(false);
}

DisplaySettings::DisplaySize DisplaySettings::getDisplaySize() const
{
    return mDisplaySize;
}

void DisplaySettings::setDisplaySize(const DisplaySize &displaySize)
{
    mDisplaySize = displaySize;
    mapDisplaySizeSettings.clear();
    switch (displaySize) {
    case DisplaySettings::ds35:
        mapDisplaySizeSettings["__DispWidth"   ]= 320;
        mapDisplaySizeSettings["__DispHeight"  ]= 240;
        mapDisplaySizeSettings["__DispHCycle"  ]= 408;
        mapDisplaySizeSettings["__DispHOffset" ]= 70;
        mapDisplaySizeSettings["__DispHSync0"  ]= 0;
        mapDisplaySizeSettings["__DispHSync1"  ]= 10;
        mapDisplaySizeSettings["__DispVCycle"  ]= 263;
        mapDisplaySizeSettings["__DispVOffset" ]= 13;
        mapDisplaySizeSettings["__DispVSync0"  ]= 0;
        mapDisplaySizeSettings["__DispVSync1"  ]= 2;
        mapDisplaySizeSettings["__DispPCLK"    ]= 6;
        mapDisplaySizeSettings["__DispSwizzle" ]= 2;
        mapDisplaySizeSettings["__DispPCLKPol" ]= 1;
        mapDisplaySizeSettings["__DispCSpread" ]= 0;
        mapDisplaySizeSettings["__DispDither"  ]= 1;
        break;
    case DisplaySettings::ds43:
        mapDisplaySizeSettings["__DispWidth"   ]= 480;
        mapDisplaySizeSettings["__DispHeight"  ]= 272;
        mapDisplaySizeSettings["__DispHCycle"  ]= 548;
        mapDisplaySizeSettings["__DispHOffset" ]= 43;
        mapDisplaySizeSettings["__DispHSync0"  ]= 0;
        mapDisplaySizeSettings["__DispHSync1"  ]= 41;
        mapDisplaySizeSettings["__DispVCycle"  ]= 292;
        mapDisplaySizeSettings["__DispVOffset" ]= 12;
        mapDisplaySizeSettings["__DispVSync0"  ]= 0;
        mapDisplaySizeSettings["__DispVSync1"  ]= 10;
        mapDisplaySizeSettings["__DispPCLK"    ]= 5;
        mapDisplaySizeSettings["__DispSwizzle" ]= 0;
        mapDisplaySizeSettings["__DispPCLKPol" ]= 1;
        mapDisplaySizeSettings["__DispCSpread" ]= 0;
        mapDisplaySizeSettings["__DispDither"  ]= 1;
        mapDisplaySizeSettings["__DispRotate"  ]= 1;
        break;
    case DisplaySettings::ds50:
        mapDisplaySizeSettings["__DispWidth"   ]= 800;
        mapDisplaySizeSettings["__DispHeight"  ]= 480;
        mapDisplaySizeSettings["__DispHCycle"  ]= 1056;
        mapDisplaySizeSettings["__DispHOffset" ]= 46;
        mapDisplaySizeSettings["__DispHSync0"  ]= 0;
        mapDisplaySizeSettings["__DispHSync1"  ]= 10;
        mapDisplaySizeSettings["__DispVCycle"  ]= 525;
        mapDisplaySizeSettings["__DispVOffset" ]= 23;
        mapDisplaySizeSettings["__DispVSync0"  ]= 0;
        mapDisplaySizeSettings["__DispVSync1"  ]= 10;
        mapDisplaySizeSettings["__DispPCLK"    ]= 2;
        mapDisplaySizeSettings["__DispSwizzle" ]= 0;
        mapDisplaySizeSettings["__DispPCLKPol" ]= 0;
        mapDisplaySizeSettings["__DispCSpread" ]= 0;
        mapDisplaySizeSettings["__DispDither"  ]= 1;
        break;
    case DisplaySettings::ds70:
        mapDisplaySizeSettings["__DispWidth"   ]= 800;
        mapDisplaySizeSettings["__DispHeight"  ]= 480;
        mapDisplaySizeSettings["__DispHCycle"  ]= 1056;
        mapDisplaySizeSettings["__DispHOffset" ]= 46;
        mapDisplaySizeSettings["__DispHSync0"  ]= 0;
        mapDisplaySizeSettings["__DispHSync1"  ]= 10;
        mapDisplaySizeSettings["__DispVCycle"  ]= 525;
        mapDisplaySizeSettings["__DispVOffset" ]= 23;
        mapDisplaySizeSettings["__DispVSync0"  ]= 0;
        mapDisplaySizeSettings["__DispVSync1"  ]= 10;
        mapDisplaySizeSettings["__DispPCLK"    ]= 2;
        mapDisplaySizeSettings["__DispSwizzle" ]= 0;
        mapDisplaySizeSettings["__DispPCLKPol" ]= 0;
        mapDisplaySizeSettings["__DispCSpread" ]= 0;
        mapDisplaySizeSettings["__DispDither"  ]= 1;
        break;
    }
}
